// Mazos de canciones de Temón. Solo datos (título, artista, disco, año): la música la pone el anfitrión con su app.
// Formato: "Título|Artista|Disco|Año".
window.DECKS = (() => {
  const raw = {
    rocknac: { name: "Rock nacional", ic: "🎸", color: "#ff5a4e", songs: [
      "De música ligera|Soda Stereo|Canción animal|1990",
      "Persiana americana|Soda Stereo|Signos|1986",
      "Prófugos|Soda Stereo|Signos|1986",
      "Nada personal|Soda Stereo|Nada personal|1985",
      "Cuando pase el temblor|Soda Stereo|Nada personal|1985",
      "En la ciudad de la furia|Soda Stereo|Doble vida|1988",
      "Trátame suavemente|Soda Stereo|Soda Stereo|1984",
      "Zoom|Soda Stereo|Sueño Stereo|1995",
      "Ella usó mi cabeza como un revólver|Soda Stereo|Sueño Stereo|1995",
      "Demoliendo hoteles|Charly García|Piano bar|1984",
      "Promesas sobre el bidet|Charly García|Piano bar|1984",
      "Los dinosaurios|Charly García|Clics modernos|1983",
      "Nos siguen pegando abajo|Charly García|Clics modernos|1983",
      "Yendo de la cama al living|Charly García|Yendo de la cama al living|1982",
      "Rezo por vos|Charly García|Parte de la religión|1987",
      "No voy en tren|Charly García|Parte de la religión|1987",
      "Seminare|Serú Girán|Serú Girán|1978",
      "Canción para mi muerte|Sui Generis|Vida|1972",
      "Rasguña las piedras|Sui Generis|Confesiones de invierno|1973",
      "Muchacha (ojos de papel)|Almendra|Almendra|1969",
      "Barro tal vez|Luis Alberto Spinetta|Kamikaze|1982",
      "Seguir viviendo sin tu amor|Luis Alberto Spinetta|Pelusón of milk|1991",
      "Durazno sangrando|Invisible|El jardín de los presentes|1976",
      "Ji ji ji|Patricio Rey y sus Redonditos de Ricota|Oktubre|1986",
      "Un poco de amor francés|Patricio Rey y sus Redonditos de Ricota|¡Bang! ¡Bang! Estás liquidado|1989",
      "Juguetes perdidos|Patricio Rey y sus Redonditos de Ricota|La mosca y la sopa|1991",
      "Flaca|Andrés Calamaro|Alta suciedad|1997",
      "Crímenes perfectos|Andrés Calamaro|Alta suciedad|1997",
      "Mil horas|Los Abuelos de la Nada|Vasos y besos|1983",
      "Costumbres argentinas|Los Abuelos de la Nada|Himno de mi corazón|1984",
      "Matador|Los Fabulosos Cadillacs|Vasos vacíos|1993",
      "Mal bicho|Los Fabulosos Cadillacs|Rey Azúcar|1995",
      "Siguiendo la luna|Los Fabulosos Cadillacs|Bares y fondas|1986",
      "Lamento boliviano|Enanitos Verdes|Big Bang|1994",
      "La muralla verde|Enanitos Verdes|Contrarreloj|1986",
      "Puente|Gustavo Cerati|Bocanada|1999",
      "Crimen|Gustavo Cerati|Ahí vamos|2006",
      "Adiós|Gustavo Cerati|Ahí vamos|2006",
      "Mañana en el Abasto|Sumo|After Chabón|1987",
      "Señor Cobranza|Bersuit Vergarabat|Libertinaje|1998",
      "La bolsa|Bersuit Vergarabat|Libertinaje|1998",
      "Spaghetti del rock|Divididos|La era de la boludez|1993",
      "El arriero|Divididos|La era de la boludez|1993",
      "Tan solo|Los Piojos|Azul|1998",
      "Irresponsables|Babasónicos|Infame|2003",
      "El loco|Babasónicos|Jessico|2001",
      "Don|Miranda!|Sin restricciones|2004",
      "Wadu wadu|Virus|Wadu-Wadu|1981",
      "Una luna de miel en la mano|Virus|Locura|1985",
      "11 y 6|Fito Páez|Giros|1985",
      "El amor después del amor|Fito Páez|El amor después del amor|1992",
      "Dar es dar|Fito Páez|El amor después del amor|1992",
      "Mariposa tecknicolor|Fito Páez|Circo beat|1994",
      "Sólo le pido a Dios|León Gieco|IV LP|1978",
      "Mujer amante|Rata Blanca|Magos, espadas y rosas|1990",
    ] },
    latino: { name: "Latino y fiesta", ic: "💃", color: "#ff4fa3", songs: [
      "Despacito|Luis Fonsi y Daddy Yankee|Vida|2017",
      "Échame la culpa|Luis Fonsi y Demi Lovato|Vida|2017",
      "Gasolina|Daddy Yankee|Barrio Fino|2004",
      "Limbo|Daddy Yankee|Prestige|2012",
      "Hips Don't Lie|Shakira|Oral Fixation Vol. 2|2006",
      "Ojos así|Shakira|¿Dónde están los ladrones?|1998",
      "Estoy aquí|Shakira|Pies descalzos|1995",
      "La tortura|Shakira y Alejandro Sanz|Fijación oral vol. 1|2005",
      "Bzrp Music Sessions, Vol. 53|Bizarrap y Shakira|Las mujeres ya no lloran|2023",
      "Livin' la vida loca|Ricky Martin|Ricky Martin|1999",
      "María|Ricky Martin|A medio vivir|1995",
      "La copa de la vida|Ricky Martin|Vuelve|1998",
      "Bailando|Enrique Iglesias|Sex and Love|2014",
      "Corazón partío|Alejandro Sanz|Más|1997",
      "La flaca|Jarabe de Palo|La flaca|1996",
      "Bonito|Jarabe de Palo|Bonito|2003",
      "Rayando el sol|Maná|Falta amor|1990",
      "Oye mi amor|Maná|¿Dónde jugarán los niños?|1992",
      "Clavado en un bar|Maná|Sueños líquidos|1997",
      "La chica de ayer|Nacha Pop|Nacha Pop|1980",
      "Me colé en una fiesta|Mecano|Mecano|1982",
      "Hijo de la luna|Mecano|Entre el cielo y el suelo|1986",
      "Torero|Chayanne|Sincero|2002",
      "Vivir mi vida|Marc Anthony|3.0|2013",
      "La gozadera|Gente de Zona y Marc Anthony|Visualízate|2015",
      "Danza kuduro|Don Omar y Lucenzo|Meet the Orphans|2010",
      "Dákiti|Bad Bunny y Jhayco|El último tour del mundo|2020",
      "Tití me preguntó|Bad Bunny|Un verano sin ti|2022",
      "Me porto bonito|Bad Bunny y Chencho Corleone|Un verano sin ti|2022",
      "Hawái|Maluma|Papi Juancho|2020",
      "Felices los 4|Maluma|F.A.M.E.|2017",
      "Tusa|Karol G y Nicki Minaj|KG0516|2019",
      "Propuesta indecente|Romeo Santos|Fórmula, Vol. 2|2013",
      "Obsesión|Aventura|We Broke the Rules|2002",
      "Suavemente|Elvis Crespo|Suavemente|1998",
      "No me arrepiento de este amor|Gilda|Corazón valiente|1995",
      "La mano de Dios|Rodrigo|A 2000|2000",
      "Lo mejor del amor|Rodrigo|A 2000|2000",
      "Mi gente|J Balvin y Willy William|Vibras|2017",
      "Ginza|J Balvin|Energía|2015",
      "Robarte un beso|Carlos Vives y Sebastián Yatra|Vives|2017",
      "La bicicleta|Carlos Vives y Shakira|Vives|2016",
      "Color esperanza|Diego Torres|Un mundo diferente|2001",
      "La camisa negra|Juanes|Mi sangre|2004",
      "A Dios le pido|Juanes|Un día normal|2002",
      "Me enamora|Juanes|La vida... es un ratico|2007",
      "Mayores|Becky G y Bad Bunny|Mala santa|2017",
      "Sin pijama|Becky G y Natti Natasha|Mala santa|2018",
      "Despechá|Rosalía|Motomami +|2022",
      "Malamente|Rosalía|El mal querer|2018",
    ] },
    clasicos: { name: "Clásicos en inglés", ic: "📼", color: "#4fd1ff", songs: [
      "Billie Jean|Michael Jackson|Thriller|1982",
      "Thriller|Michael Jackson|Thriller|1982",
      "Beat It|Michael Jackson|Thriller|1982",
      "Black or White|Michael Jackson|Dangerous|1991",
      "Bohemian Rhapsody|Queen|A Night at the Opera|1975",
      "Don't Stop Me Now|Queen|Jazz|1978",
      "Another One Bites the Dust|Queen|The Game|1980",
      "Under Pressure|Queen y David Bowie|Hot Space|1981",
      "Like a Prayer|Madonna|Like a Prayer|1989",
      "Like a Virgin|Madonna|Like a Virgin|1984",
      "Material Girl|Madonna|Like a Virgin|1984",
      "Vogue|Madonna|I'm Breathless|1990",
      "Smells Like Teen Spirit|Nirvana|Nevermind|1991",
      "Sweet Child O' Mine|Guns N' Roses|Appetite for Destruction|1987",
      "Hotel California|Eagles|Hotel California|1976",
      "Imagine|John Lennon|Imagine|1971",
      "Let It Be|The Beatles|Let It Be|1970",
      "Here Comes the Sun|The Beatles|Abbey Road|1969",
      "Yesterday|The Beatles|Help!|1965",
      "(I Can't Get No) Satisfaction|The Rolling Stones|Out of Our Heads|1965",
      "Like a Rolling Stone|Bob Dylan|Highway 61 Revisited|1965",
      "Respect|Aretha Franklin|I Never Loved a Man the Way I Love You|1967",
      "Wonderwall|Oasis|(What's the Story) Morning Glory?|1995",
      "With or Without You|U2|The Joshua Tree|1987",
      "Every Breath You Take|The Police|Synchronicity|1983",
      "Take On Me|a-ha|Hunting High and Low|1985",
      "Livin' on a Prayer|Bon Jovi|Slippery When Wet|1986",
      "Africa|Toto|Toto IV|1982",
      "Girls Just Want to Have Fun|Cyndi Lauper|She's So Unusual|1983",
      "Time After Time|Cyndi Lauper|She's So Unusual|1984",
      "I Will Survive|Gloria Gaynor|Love Tracks|1978",
      "Stayin' Alive|Bee Gees|Saturday Night Fever|1977",
      "Dancing Queen|ABBA|Arrival|1976",
      "Le Freak|Chic|C'est Chic|1978",
      "Y.M.C.A.|Village People|Cruisin'|1978",
      "Wannabe|Spice Girls|Spice|1996",
      "...Baby One More Time|Britney Spears|...Baby One More Time|1998",
      "I Want It That Way|Backstreet Boys|Millennium|1999",
      "Smooth|Santana y Rob Thomas|Supernatural|1999",
      "Zombie|The Cranberries|No Need to Argue|1994",
      "Losing My Religion|R.E.M.|Out of Time|1991",
      "Creep|Radiohead|Pablo Honey|1992",
      "Wish You Were Here|Pink Floyd|Wish You Were Here|1975",
      "Another Brick in the Wall (Part 2)|Pink Floyd|The Wall|1979",
      "Highway to Hell|AC/DC|Highway to Hell|1979",
      "Back in Black|AC/DC|Back in Black|1980",
      "Enter Sandman|Metallica|Metallica|1991",
      "Nothing Else Matters|Metallica|Metallica|1991",
      "Sweet Dreams (Are Made of This)|Eurythmics|Sweet Dreams (Are Made of This)|1983",
      "Total Eclipse of the Heart|Bonnie Tyler|Faster Than the Speed of Night|1983",
      "Never Gonna Give You Up|Rick Astley|Whenever You Need Somebody|1987",
      "Purple Rain|Prince|Purple Rain|1984",
      "Kiss|Prince|Parade|1986",
      "Don't Stop Believin'|Journey|Escape|1981",
      "Eye of the Tiger|Survivor|Eye of the Tiger|1982",
      "Born in the U.S.A.|Bruce Springsteen|Born in the U.S.A.|1984",
      "Jump|Van Halen|1984|1984",
      "I Will Always Love You|Whitney Houston|The Bodyguard|1992",
      "My Heart Will Go On|Céline Dion|Let's Talk About Love|1997",
      "Torn|Natalie Imbruglia|Left of the Middle|1997",
    ] },
    hits: { name: "Hits en inglés 2000+", ic: "🔥", color: "#ffb627", songs: [
      "Crazy in Love|Beyoncé|Dangerously in Love|2003",
      "Halo|Beyoncé|I Am... Sasha Fierce|2008",
      "Single Ladies (Put a Ring on It)|Beyoncé|I Am... Sasha Fierce|2008",
      "Hey Ya!|Outkast|Speakerboxxx/The Love Below|2003",
      "Mr. Brightside|The Killers|Hot Fuss|2004",
      "Seven Nation Army|The White Stripes|Elephant|2003",
      "Umbrella|Rihanna|Good Girl Gone Bad|2007",
      "Diamonds|Rihanna|Unapologetic|2012",
      "We Found Love|Rihanna y Calvin Harris|Talk That Talk|2011",
      "Rolling in the Deep|Adele|21|2010",
      "Someone Like You|Adele|21|2011",
      "Rehab|Amy Winehouse|Back to Black|2006",
      "Uptown Funk|Mark Ronson y Bruno Mars|Uptown Special|2014",
      "Locked Out of Heaven|Bruno Mars|Unorthodox Jukebox|2012",
      "Just the Way You Are|Bruno Mars|Doo-Wops & Hooligans|2010",
      "Shape of You|Ed Sheeran|÷|2017",
      "Thinking Out Loud|Ed Sheeran|x|2014",
      "Blinding Lights|The Weeknd|After Hours|2019",
      "Can't Feel My Face|The Weeknd|Beauty Behind the Madness|2015",
      "Starboy|The Weeknd y Daft Punk|Starboy|2016",
      "Bad Guy|Billie Eilish|When We All Fall Asleep, Where Do We Go?|2019",
      "Happy|Pharrell Williams|Despicable Me 2|2013",
      "Get Lucky|Daft Punk y Pharrell Williams|Random Access Memories|2013",
      "Poker Face|Lady Gaga|The Fame|2008",
      "Just Dance|Lady Gaga|The Fame|2008",
      "Bad Romance|Lady Gaga|The Fame Monster|2009",
      "Shallow|Lady Gaga y Bradley Cooper|A Star Is Born|2018",
      "Viva la Vida|Coldplay|Viva la Vida or Death and All His Friends|2008",
      "Yellow|Coldplay|Parachutes|2000",
      "Clocks|Coldplay|A Rush of Blood to the Head|2002",
      "Numb|Linkin Park|Meteora|2003",
      "In the End|Linkin Park|Hybrid Theory|2000",
      "Somebody That I Used to Know|Gotye|Making Mirrors|2011",
      "Toxic|Britney Spears|In the Zone|2003",
      "Since U Been Gone|Kelly Clarkson|Breakaway|2004",
      "Party Rock Anthem|LMFAO|Sorry for Party Rocking|2011",
      "I Gotta Feeling|The Black Eyed Peas|The E.N.D.|2009",
      "Where Is the Love?|The Black Eyed Peas|Elephunk|2003",
      "Firework|Katy Perry|Teenage Dream|2010",
      "Roar|Katy Perry|Prism|2013",
      "Love Story|Taylor Swift|Fearless|2008",
      "Shake It Off|Taylor Swift|1989|2014",
      "Anti-Hero|Taylor Swift|Midnights|2022",
      "Don't Start Now|Dua Lipa|Future Nostalgia|2019",
      "Levitating|Dua Lipa|Future Nostalgia|2020",
      "As It Was|Harry Styles|Harry's House|2022",
      "drivers license|Olivia Rodrigo|SOUR|2021",
      "Flowers|Miley Cyrus|Endless Summer Vacation|2023",
      "Wrecking Ball|Miley Cyrus|Bangerz|2013",
      "Stay|The Kid LAROI y Justin Bieber|F*ck Love 3: Over You|2021",
      "Sorry|Justin Bieber|Purpose|2015",
      "Counting Stars|OneRepublic|Native|2013",
      "Radioactive|Imagine Dragons|Night Visions|2012",
      "Believer|Imagine Dragons|Evolve|2017",
      "Pumped Up Kicks|Foster the People|Torches|2010",
      "Royals|Lorde|Pure Heroine|2013",
      "Chandelier|Sia|1000 Forms of Fear|2014",
      "Cheap Thrills|Sia|This Is Acting|2016",
    ] },
  };
  const out = {};
  for (const [id, d] of Object.entries(raw)) {
    out[id] = { name: d.name, ic: d.ic, color: d.color, songs: d.songs.map((s) => {
      const [title, artist, album, year] = s.split("|");
      return { id: id + ":" + title, title, artist, album, year };
    }) };
  }
  return out;
})();
