// Mazos de canciones de Temón. Solo datos (título, artista, disco, año): la música la pone el anfitrión con su app.
// Formato: "Título|Artista|Disco|Año".
window.DECKS = (() => {
  const raw = {
    rocknac: { name: "Rock nacional", ic: "🎸", color: "#ff5a4e", songs: [
      "De música ligera|Soda Stereo|Canción animal|1990",
      "Persiana americana|Soda Stereo|Signos|1986",
      "Prófugos|Soda Stereo|Signos|1986",
      "Nada personal|Soda Stereo|Nada personal|1985",
      "Cuando pase el temblor|Soda Stereo|Nada personal|1985",
      "En la ciudad de la furia|Soda Stereo|Doble vida|1988",
      "Trátame suavemente|Soda Stereo|Soda Stereo|1984",
      "Zoom|Soda Stereo|Sueño Stereo|1995",
      "Ella usó mi cabeza como un revólver|Soda Stereo|Sueño Stereo|1995",
      "Demoliendo hoteles|Charly García|Piano bar|1984",
      "Promesas sobre el bidet|Charly García|Piano bar|1984",
      "Los dinosaurios|Charly García|Clics modernos|1983",
      "Nos siguen pegando abajo|Charly García|Clics modernos|1983",
      "Yendo de la cama al living|Charly García|Yendo de la cama al living|1982",
      "Rezo por vos|Charly García|Parte de la religión|1987",
      "No voy en tren|Charly García|Parte de la religión|1987",
      "Seminare|Serú Girán|Serú Girán|1978",
      "Canción para mi muerte|Sui Generis|Vida|1972",
      "Rasguña las piedras|Sui Generis|Confesiones de invierno|1973",
      "Muchacha (ojos de papel)|Almendra|Almendra|1969",
      "Barro tal vez|Luis Alberto Spinetta|Kamikaze|1982",
      "Seguir viviendo sin tu amor|Luis Alberto Spinetta|Pelusón of milk|1991",
      "Durazno sangrando|Invisible|El jardín de los presentes|1976",
      "Ji ji ji|Patricio Rey y sus Redonditos de Ricota|Oktubre|1986",
      "Un poco de amor francés|Patricio Rey y sus Redonditos de Ricota|¡Bang! ¡Bang! Estás liquidado|1989",
      "Juguetes perdidos|Patricio Rey y sus Redonditos de Ricota|La mosca y la sopa|1991",
      "Flaca|Andrés Calamaro|Alta suciedad|1997",
      "Crímenes perfectos|Andrés Calamaro|Alta suciedad|1997",
      "Mil horas|Los Abuelos de la Nada|Vasos y besos|1983",
      "Costumbres argentinas|Los Abuelos de la Nada|Himno de mi corazón|1984",
      "Matador|Los Fabulosos Cadillacs|Vasos vacíos|1993",
      "Mal bicho|Los Fabulosos Cadillacs|Rey Azúcar|1995",
      "Siguiendo la luna|Los Fabulosos Cadillacs|Bares y fondas|1986",
      "Lamento boliviano|Enanitos Verdes|Big Bang|1994",
      "La muralla verde|Enanitos Verdes|Contrarreloj|1986",
      "Puente|Gustavo Cerati|Bocanada|1999",
      "Crimen|Gustavo Cerati|Ahí vamos|2006",
      "Adiós|Gustavo Cerati|Ahí vamos|2006",
      "Mañana en el Abasto|Sumo|After Chabón|1987",
      "Señor Cobranza|Bersuit Vergarabat|Libertinaje|1998",
      "La bolsa|Bersuit Vergarabat|Libertinaje|1998",
      "Spaghetti del rock|Divididos|La era de la boludez|1993",
      "El arriero|Divididos|La era de la boludez|1993",
      "Tan solo|Los Piojos|Azul|1998",
      "Irresponsables|Babasónicos|Infame|2003",
      "El loco|Babasónicos|Jessico|2001",
      "Don|Miranda!|Sin restricciones|2004",
      "Wadu wadu|Virus|Wadu-Wadu|1981",
      "Una luna de miel en la mano|Virus|Locura|1985",
      "11 y 6|Fito Páez|Giros|1985",
      "El amor después del amor|Fito Páez|El amor después del amor|1992",
      "Dar es dar|Fito Páez|El amor después del amor|1992",
      "Mariposa tecknicolor|Fito Páez|Circo beat|1994",
      "Sólo le pido a Dios|León Gieco|IV LP|1978",
      "Mujer amante|Rata Blanca|Magos, espadas y rosas|1990",
      "Sobredosis de TV|Soda Stereo|Soda Stereo|1984",
      "Te hacen falta vitaminas|Soda Stereo|Soda Stereo|1984",
      "Juego de seducción|Soda Stereo|Nada personal|1985",
      "Signos|Soda Stereo|Signos|1986",
      "Hombre al agua|Soda Stereo|Doble vida|1988",
      "Un millón de años luz|Soda Stereo|Canción animal|1990",
      "Té para tres|Soda Stereo|Canción animal|1990",
      "Sueles dejarme solo|Soda Stereo|Dynamo|1992",
      "Primavera 0|Soda Stereo|Sueño Stereo|1995",
      "Lago en el cielo|Gustavo Cerati|Amor amarillo|1993",
      "Amor amarillo|Gustavo Cerati|Amor amarillo|1993",
      "Paseo inmoral|Gustavo Cerati|Bocanada|1999",
      "Cosas imposibles|Gustavo Cerati|Siempre es hoy|2002",
      "Engaña|Gustavo Cerati|Siempre es hoy|2002",
      "Fuerza natural|Gustavo Cerati|Fuerza natural|2009",
      "Déjà vu|Gustavo Cerati|Fuerza natural|2009",
      "Inconsciente colectivo|Charly García|Yendo de la cama al living|1982",
      "Cerca de la revolución|Charly García|Parte de la religión|1987",
      "Fanky|Charly García|Cómo conseguir chicas|1989",
      "Influencia|Charly García|Influencia|2002",
      "Hablando a tu corazón|Charly García y Pedro Aznar|Tango|1986",
      "Natalio Ruiz, el hombrecito del sombrero gris|Sui Generis|Vida|1972",
      "Toma el tren hacia el sur|Sui Generis|Vida|1972",
      "Confesiones de invierno|Sui Generis|Confesiones de invierno|1973",
      "Bienvenidos al tren|Sui Generis|Confesiones de invierno|1973",
      "Esperando nacer|Serú Girán|Serú Girán|1978",
      "Viernes 3 AM|Serú Girán|La grasa de las capitales|1979",
      "Desarma y sangra|Serú Girán|La grasa de las capitales|1979",
      "Canción de Alicia en el país|Serú Girán|Bicicleta|1980",
      "Llorando en el espejo|Serú Girán|Bicicleta|1980",
      "Peperina|Serú Girán|Peperina|1981",
      "Ana no duerme|Almendra|Almendra|1969",
      "Plegaria para un niño dormido|Almendra|Almendra|1969",
      "Bajan|Pescado Rabioso|Artaud|1973",
      "Cementerio club|Pescado Rabioso|Artaud|1973",
      "El anillo del capitán Beto|Invisible|El jardín de los presentes|1976",
      "Alma de diamante|Spinetta Jade|Alma de diamante|1980",
      "La bestia pop|Patricio Rey y sus Redonditos de Ricota|Gulp!|1985",
      "Ya nadie va a escuchar tu remera|Patricio Rey y sus Redonditos de Ricota|Gulp!|1985",
      "Vencedores vencidos|Patricio Rey y sus Redonditos de Ricota|Un baión para el ojo idiota|1988",
      "Todo un palo|Patricio Rey y sus Redonditos de Ricota|Un baión para el ojo idiota|1988",
      "Queso ruso|Patricio Rey y sus Redonditos de Ricota|La mosca y la sopa|1991",
      "El pibe de los astilleros|Patricio Rey y sus Redonditos de Ricota|Lobo suelto, cordero atado|1993",
      "Esa estrella era mi lujo|Patricio Rey y sus Redonditos de Ricota|Luzbelito|1996",
      "Ciudad de pobres corazones|Fito Páez|Ciudad de pobres corazones|1987",
      "Y dale alegría a mi corazón|Fito Páez|Ey!|1988",
      "Al lado del camino|Fito Páez|Abre|1999",
      "Estadio Azteca|Andrés Calamaro|Honestidad brutal|1999",
      "Paloma|Andrés Calamaro|Honestidad brutal|1999",
      "La parte de adelante|Andrés Calamaro|El salmón|2000",
      "Sin documentos|Los Rodríguez|Sin documentos|1993",
      "Dulce condena|Los Rodríguez|Sin documentos|1993",
      "Engánchate conmigo|Los Rodríguez|Palabras más, palabras menos|1995",
      "Sin gamulán|Los Abuelos de la Nada|Los Abuelos de la Nada|1982",
      "Chalamán|Los Abuelos de la Nada|Los Abuelos de la Nada|1982",
      "Tristeza de la ciudad|Los Abuelos de la Nada|Vasos y besos|1983",
      "Himno de mi corazón|Los Abuelos de la Nada|Himno de mi corazón|1984",
      "Imágenes paganas|Virus|Locura|1985",
      "Pronta entrega|Virus|Superficies de placer|1987",
      "Encuentro con el diablo|Virus|Superficies de placer|1987",
      "Yo te avisé|Los Fabulosos Cadillacs|Yo te avisé!!|1987",
      "Estoy harto de verte con otros|Los Fabulosos Cadillacs|Yo te avisé!!|1987",
      "Manuel Santillán, el León|Los Fabulosos Cadillacs|El León|1992",
      "Calaveras y diablitos|Los Fabulosos Cadillacs|Fabulosos Calavera|1997",
      "El 38|Divididos|40 dibujos ahí en el piso|1989",
      "¿Qué ves?|Divididos|Acariciando lo áspero|1991",
      "Paisano de Hurlingham|Divididos|Acariciando lo áspero|1991",
      "Par mil|Divididos|Acariciando lo áspero|1991",
      "Ala delta|Divididos|Gol de mujer|1998",
      "La rubia tarada|Sumo|Llegando los monos|1986",
      "Los viejos vinagres|Sumo|Llegando los monos|1986",
      "Estallando desde el océano|Sumo|After Chabón|1987",
      "Babilonia|Los Piojos|Ay ay ay|1994",
      "El farolito|Los Piojos|Tercer arco|1996",
      "Como Alí|Los Piojos|Verde paisaje del infierno|2000",
      "Balada del diablo y la muerte|La Renga|Despedazado por mil partes|1996",
      "Panic show|La Renga|Despedazado por mil partes|1996",
      "Yo tomo|Bersuit Vergarabat|Hijos del culo|2000",
      "El tiempo no para|Bersuit Vergarabat|Hijos del culo|2000",
      "Sencillamente|Bersuit Vergarabat|La argentinidad al palo|2004",
      "Putita|Babasónicos|Jessico|2001",
      "Pijamas|Babasónicos|Infame|2003",
      "Microdancing|Babasónicos|Anoche|2005",
      "Yegua|Babasónicos|Mucho|2008",
      "Hacelo por mí|Attaque 77|Un día perfecto|1997",
      "Arrancacorazones|Attaque 77|Un día perfecto|1997",
      "Antes y después|Ciro y los Persas|Espejos|2010",
      "La guitarra|Los Auténticos Decadentes|Mi vida loca|1995",
      "Yendo a la casa de Damián|El Cuarteto de Nos|Raro|2006",
      "Ya no sé qué hacer conmigo|El Cuarteto de Nos|Raro|2006",
      "Me amo|El Cuarteto de Nos|Bipolar|2009",
      "El hijo de Hernández|El Cuarteto de Nos|Bipolar|2009",
      "Lo malo de ser bueno|El Cuarteto de Nos|Porfiado|2012",
      "Dale!|Catupecu Machu|Dale!|1997",
      "Y lo que quiero es que pises sin el suelo|Catupecu Machu|Cuentos decapitados|2004",
      "Mujeres bellas y fuertes|Él Mató a un Policía Motorizado|La dinastía Scorpio|2012",
      "Más o menos bien|Él Mató a un Policía Motorizado|La dinastía Scorpio|2012",
      "El tren de las 16|Pappo's Blues|Pappo's Blues Volumen 1|1971",
      "Presente (El tiempo es como el viento)|Vox Dei|Caliente|1970",
      "Jugo de tomate frío|Manal|Manal|1970",
      "Avellaneda blues|Manal|Manal|1970",
      "La balsa|Los Gatos|Los Gatos|1967",
      "En el país de la libertad|León Gieco|León Gieco|1973",
      "Hombres de hierro|León Gieco|León Gieco|1973",
      "Pensar en nada|León Gieco|Pensar en nada|1981",
      "La memoria|León Gieco|Bandidos rurales|2001",
      "El ángel de la bicicleta|León Gieco|Bandidos rurales|2001",
      "Pensé que se trataba de cieguitos|Los Twist|La dicha en movimiento|1983",
      "La leyenda del hada y el mago|Rata Blanca|Magos, espadas y rosas|1990",
      "Yo te diré|Miranda!|Sin restricciones|2004",
      "Prisionero|Miranda!|El disco de tu corazón|2007",
      "Tu misterioso alguien|Miranda!|El disco de tu corazón|2007",
      "Ella|Tan Biónica|Obsesionario|2010",
      "Beautiful|Tan Biónica|Obsesionario|2010",
      "La melodía de Dios|Tan Biónica|Destinología|2013",
      "Ciudad mágica|Tan Biónica|Destinología|2013",
      "Luz de día|Enanitos Verdes|Contrarreloj|1986",
      "Tu cárcel|Enanitos Verdes|Big Bang|1994",
      "Tirá para arriba|Miguel Mateos|Solos en América|1986",
      "Cuando seas grande|Miguel Mateos|Solos en América|1986",
      "Pupilas lejanas|Los Pericos|Big Yuyo|1992",
      "Uno, dos, ultraviolento|Los Violadores|Y ahora qué pasa, ¿eh?|1985",
      "Los caminos de la vida|Vicentico|Los rayos|2010",
      "Giros|Fito Páez|Giros|1985",
    ] },
    latino: { name: "Latino, cumbia y fiesta", ic: "💃", color: "#ff4fa3", songs: [
      "Despacito|Luis Fonsi y Daddy Yankee|Vida|2017",
      "Échame la culpa|Luis Fonsi y Demi Lovato|Vida|2017",
      "Gasolina|Daddy Yankee|Barrio Fino|2004",
      "Limbo|Daddy Yankee|Prestige|2012",
      "Hips Don't Lie|Shakira|Oral Fixation Vol. 2|2006",
      "Ojos así|Shakira|¿Dónde están los ladrones?|1998",
      "Estoy aquí|Shakira|Pies descalzos|1995",
      "La tortura|Shakira y Alejandro Sanz|Fijación oral vol. 1|2005",
      "Bzrp Music Sessions, Vol. 53|Bizarrap y Shakira|Las mujeres ya no lloran|2023",
      "Livin' la vida loca|Ricky Martin|Ricky Martin|1999",
      "María|Ricky Martin|A medio vivir|1995",
      "La copa de la vida|Ricky Martin|Vuelve|1998",
      "Bailando|Enrique Iglesias|Sex and Love|2014",
      "Corazón partío|Alejandro Sanz|Más|1997",
      "La flaca|Jarabe de Palo|La flaca|1996",
      "Bonito|Jarabe de Palo|Bonito|2003",
      "Rayando el sol|Maná|Falta amor|1990",
      "Oye mi amor|Maná|¿Dónde jugarán los niños?|1992",
      "Clavado en un bar|Maná|Sueños líquidos|1997",
      "La chica de ayer|Nacha Pop|Nacha Pop|1980",
      "Me colé en una fiesta|Mecano|Mecano|1982",
      "Hijo de la luna|Mecano|Entre el cielo y el suelo|1986",
      "Torero|Chayanne|Sincero|2002",
      "Vivir mi vida|Marc Anthony|3.0|2013",
      "La gozadera|Gente de Zona y Marc Anthony|Visualízate|2015",
      "Danza kuduro|Don Omar y Lucenzo|Meet the Orphans|2010",
      "Dákiti|Bad Bunny y Jhayco|El último tour del mundo|2020",
      "Tití me preguntó|Bad Bunny|Un verano sin ti|2022",
      "Me porto bonito|Bad Bunny y Chencho Corleone|Un verano sin ti|2022",
      "Hawái|Maluma|Papi Juancho|2020",
      "Felices los 4|Maluma|F.A.M.E.|2017",
      "Tusa|Karol G y Nicki Minaj|KG0516|2019",
      "Propuesta indecente|Romeo Santos|Fórmula, Vol. 2|2013",
      "Obsesión|Aventura|We Broke the Rules|2002",
      "Suavemente|Elvis Crespo|Suavemente|1998",
      "No me arrepiento de este amor|Gilda|Corazón valiente|1995",
      "La mano de Dios|Rodrigo|A 2000|2000",
      "Lo mejor del amor|Rodrigo|A 2000|2000",
      "Mi gente|J Balvin y Willy William|Vibras|2017",
      "Ginza|J Balvin|Energía|2015",
      "Robarte un beso|Carlos Vives y Sebastián Yatra|Vives|2017",
      "La bicicleta|Carlos Vives y Shakira|Vives|2016",
      "Color esperanza|Diego Torres|Un mundo diferente|2001",
      "La camisa negra|Juanes|Mi sangre|2004",
      "A Dios le pido|Juanes|Un día normal|2002",
      "Me enamora|Juanes|La vida... es un ratico|2007",
      "Mayores|Becky G y Bad Bunny|Mala santa|2017",
      "Sin pijama|Becky G y Natti Natasha|Mala santa|2018",
      "Despechá|Rosalía|Motomami +|2022",
      "Malamente|Rosalía|El mal querer|2018",
      "Whenever, Wherever|Shakira|Laundry Service|2001",
      "Waka Waka (Esto es África)|Shakira|Sale el sol|2010",
      "Chantaje|Shakira y Maluma|El Dorado|2016",
      "Loca|Shakira y El Cata|Sale el sol|2010",
      "Te felicito|Shakira y Rauw Alejandro|Las mujeres ya no lloran|2022",
      "Vente pa' ca|Ricky Martin y Maluma|Vente pa' ca|2016",
      "Pégate|Ricky Martin|MTV Unplugged|2006",
      "Lo mejor de mi vida eres tú|Ricky Martin y Natalia Jiménez|Música + alma + sexo|2011",
      "Vuelve|Ricky Martin|Vuelve|1998",
      "Lo que pasó, pasó|Daddy Yankee|Barrio fino|2004",
      "Rompe|Daddy Yankee|Barrio fino en directo|2005",
      "Con calma|Daddy Yankee y Snow|Con calma|2019",
      "Dura|Daddy Yankee|Dura|2018",
      "Shaky Shaky|Daddy Yankee|Shaky Shaky|2016",
      "Llamado de emergencia|Daddy Yankee|Talento de barrio|2008",
      "Callaíta|Bad Bunny y Tainy|Callaíta|2019",
      "Safaera|Bad Bunny, Jowell & Randy y Ñengo Flow|YHLQMDLG|2020",
      "Yo perreo sola|Bad Bunny|YHLQMDLG|2020",
      "Ojitos lindos|Bad Bunny y Bomba Estéreo|Un verano sin ti|2022",
      "Monaco|Bad Bunny|Nadie sabe lo que va a pasar mañana|2023",
      "DtMF|Bad Bunny|Debí tirar más fotos|2025",
      "6 AM|J Balvin y Farruko|La familia|2013",
      "Machika|J Balvin, Jeon y Anitta|Vibras|2018",
      "Rojo|J Balvin|Colores|2020",
      "La canción|J Balvin y Bad Bunny|Oasis|2019",
      "Qué pretendes|J Balvin y Bad Bunny|Oasis|2019",
      "Qué más pues?|J Balvin y María Becerra|Qué más pues?|2021",
      "Bichota|Karol G|KG0516|2020",
      "Provenza|Karol G|Mañana será bonito|2022",
      "TQG|Karol G y Shakira|Mañana será bonito|2023",
      "Ahora me llama|Karol G y Bad Bunny|Unstoppable|2017",
      "Qlona|Karol G y Peso Pluma|Mañana será bonito (Bichota Season)|2023",
      "Si antes te hubiera conocido|Karol G|Tropicoqueta|2024",
      "Mamiii|Becky G y Karol G|Esquemas|2022",
      "Borró cassette|Maluma|Pretty Boy, Dirty Boy|2015",
      "El préstamo|Maluma|F.A.M.E.|2018",
      "Corazón|Maluma y Nego do Borel|F.A.M.E.|2017",
      "11 PM|Maluma|11:11|2019",
      "Taki Taki|DJ Snake, Selena Gomez, Ozuna y Cardi B|Carte Blanche|2018",
      "Baila baila baila|Ozuna|Nibiru|2019",
      "Se preparó|Ozuna|Odisea|2017",
      "El farsante|Ozuna|Odisea|2017",
      "Caramelo|Ozuna|ENOC|2020",
      "Hey mor|Ozuna y Feid|Ozutochi|2022",
      "Criminal|Natti Natasha y Ozuna|IlumiNatti|2017",
      "El perdón|Nicky Jam y Enrique Iglesias|Fénix|2015",
      "Hasta el amanecer|Nicky Jam|Fénix|2016",
      "X|Nicky Jam y J Balvin|X|2018",
      "Rakata|Wisin & Yandel|Pa'l mundo|2005",
      "Sexy movimiento|Wisin & Yandel|Wisin vs. Yandel: Los extraterrestres|2007",
      "Abusadora|Wisin & Yandel|La revolución|2009",
      "Algo me gusta de ti|Wisin & Yandel, Chris Brown y T-Pain|Líderes|2012",
      "Escápate conmigo|Wisin y Ozuna|Escápate conmigo|2017",
      "Dale Don dale|Don Omar|The Last Don|2003",
      "Pobre diabla|Don Omar|The Last Don|2003",
      "Salió el sol|Don Omar|iDon|2009",
      "Ella y yo|Aventura y Don Omar|God's Project|2005",
      "Eres mía|Romeo Santos|Fórmula, Vol. 2|2014",
      "Odio|Romeo Santos y Drake|Fórmula, Vol. 2|2014",
      "Promise|Romeo Santos y Usher|Fórmula, Vol. 1|2011",
      "You|Romeo Santos|Fórmula, Vol. 1|2011",
      "Imitadora|Romeo Santos|Golden|2017",
      "Un beso|Aventura|Love & Hate|2003",
      "Cuando volverás|Aventura|Generation Next|1999",
      "Mi corazoncito|Aventura|God's Project|2005",
      "Dile al amor|Aventura|K.O.B. Live|2006",
      "Valió la pena|Marc Anthony|Valió la pena|2004",
      "Ahora quién|Marc Anthony|Sigo siendo yo|2006",
      "Tu amor me hace bien|Marc Anthony|Amar sin mentiras|2004",
      "Y hubo alguien|Marc Anthony|Contra la corriente|1997",
      "Flor pálida|Marc Anthony|3.0|2013",
      "Qué precio tiene el cielo|Marc Anthony|Todo a su tiempo|1995",
      "Ojalá que llueva café|Juan Luis Guerra y 4.40|Ojalá que llueva café|1989",
      "Burbujas de amor|Juan Luis Guerra y 4.40|Bachata rosa|1990",
      "A pedir su mano|Juan Luis Guerra y 4.40|Bachata rosa|1990",
      "Las avispas|Juan Luis Guerra|Para ti|2004",
      "La travesía|Juan Luis Guerra|La llave de mi corazón|2007",
      "La gota fría|Carlos Vives|Clásicos de la provincia|1993",
      "Fruta fresca|Carlos Vives|El amor de mi tierra|1999",
      "Volví a nacer|Carlos Vives|Corazón profundo|2012",
      "Es por ti|Juanes|Un día normal|2002",
      "Volverte a ver|Juanes|Mi sangre|2004",
      "Súbeme la radio|Enrique Iglesias, Descemer Bueno y Zion & Lennox|Súbeme la radio|2017",
      "Duele el corazón|Enrique Iglesias y Wisin|Duele el corazón|2016",
      "Experiencia religiosa|Enrique Iglesias|Enrique Iglesias|1995",
      "Cuando me enamoro|Enrique Iglesias y Juan Luis Guerra|Euphoria|2010",
      "Salomé|Chayanne|Atado a tu amor|1998",
      "Provócame|Chayanne|Provócame|1992",
      "Dejaría todo|Chayanne|Atado a tu amor|1998",
      "Amor a la mexicana|Thalía|Amor a la mexicana|1997",
      "Piel morena|Thalía|En éxtasis|1995",
      "Arrasando|Thalía|Arrasando|2000",
      "A quién le importa|Thalía|Thalía|2002",
      "Mío|Paulina Rubio|La chica dorada|1992",
      "Y yo sigo aquí|Paulina Rubio|Paulina|2000",
      "Lo haré por ti|Paulina Rubio|Paulina|2000",
      "Ni una sola palabra|Paulina Rubio|Ananda|2006",
      "Suave|Luis Miguel|Aries|1993",
      "Será que no me amas|Luis Miguel|20 años|1990",
      "Ahora te puedes marchar|Luis Miguel|Soy como quiero ser|1987",
      "Mi tierra|Gloria Estefan|Mi tierra|1993",
      "Abriendo puertas|Gloria Estefan|Abriendo puertas|1995",
      "La vida es un carnaval|Celia Cruz|Mi vida es cantar|1998",
      "La negra tiene tumbao|Celia Cruz|La negra tiene tumbao|2001",
      "Ríe y llora|Celia Cruz|Regalo del alma|2003",
      "Tu sonrisa|Elvis Crespo|Suavemente|1998",
      "Píntame|Elvis Crespo|Píntame|1999",
      "Con altura|Rosalía y J Balvin|Con altura|2019",
      "Saoko|Rosalía|Motomami|2022",
      "La fama|Rosalía y The Weeknd|Motomami|2021",
      "Di mi nombre|Rosalía|El mal querer|2018",
      "Bzrp Music Sessions, Vol. 52|Bizarrap y Quevedo|Bzrp Music Sessions, Vol. 52|2022",
      "Bzrp Music Sessions, Vol. 41|Bizarrap y Nathy Peluso|Bzrp Music Sessions, Vol. 41|2020",
      "Bzrp Music Sessions, Vol. 50|Bizarrap y Duki|Bzrp Music Sessions, Vol. 50|2022",
      "Bzrp Music Sessions, Vol. 55|Bizarrap y Peso Pluma|Bzrp Music Sessions, Vol. 55|2023",
      "She Don't Give a FO|Duki y Khea|She Don't Give a FO|2017",
      "Goteo|Duki|Goteo|2019",
      "Miénteme|Tini y María Becerra|Miénteme|2021",
      "Cupido|Tini|Cupido|2023",
      "Ramen para dos|María Becerra y Paulo Londra|La nena de Argentina|2022",
      "Wapo traketero|Nicki Nicole|Recuerdos|2019",
      "Mamichula|Trueno y Nicki Nicole|Atrevido|2020",
      "Como si no importara|Emilia y Duki|Tú crees en mí?|2022",
      "Dance Crip|Trueno|Bien o mal|2022",
      "Todo de ti|Rauw Alejandro|Vice Versa|2021",
      "Desesperados|Rauw Alejandro y Chencho Corleone|Vice Versa|2021",
      "Punto 40|Rauw Alejandro y Baby Rasta|Saturno|2022",
      "Normal|Feid|Feliz cumpleaños Ferxxo te pirateamos el álbum|2022",
      "Feliz cumpleaños Ferxxo|Feid|Feliz cumpleaños Ferxxo te pirateamos el álbum|2022",
      "Luna|Feid y ATL Jacob|Mor, No le temas a la oscuridad|2023",
      "Classy 101|Feid y Young Miko|Mor, No le temas a la oscuridad|2023",
      "Lala|Myke Towers|La vida es una|2023",
      "Bandido|Myke Towers y Juhn|Easy Money Baby|2020",
      "Tacones rojos|Sebastián Yatra|Dharma|2021",
      "Traicionera|Sebastián Yatra|Mantra|2016",
      "Pareja del año|Sebastián Yatra y Myke Towers|Dharma|2021",
      "Vida de rico|Camilo|Mis manos|2020",
      "Tutu|Camilo y Pedro Capó|Por primera vez|2019",
      "La bachata|Manuel Turizo|2000|2022",
      "Una lady como tú|Manuel Turizo|ADN|2016",
      "El merengue|Marshmello y Manuel Turizo|El merengue|2023",
      "Ella baila sola|Eslabon Armado y Peso Pluma|Desvelado|2023",
      "Un x100to|Grupo Frontera y Bad Bunny|El comienzo|2023",
      "Pepas|Farruko|La 167|2021",
      "Calma (remix)|Pedro Capó y Farruko|Calma|2018",
      "Stand by Me|Prince Royce|Prince Royce|2010",
      "Darte un beso|Prince Royce|Soy el mismo|2013",
      "Macarena|Los del Río|A mí me gusta|1993",
      "Aserejé|Las Ketchup|Hijas del tomate|2002",
      "Sofia|Álvaro Soler|Eterno agosto|2016",
      "El mismo sol|Álvaro Soler|Eterno agosto|2015",
      "Lo malo|Aitana y Ana Guerra|Lo malo|2018",
      "Pa' que retozen|Tego Calderón|El abayarde|2002",
      "Mayor que yo|Baby Ranks, Daddy Yankee, Tonny Tun Tun, Wisin & Yandel y Héctor el Father|Mas flow 2|2005",
      "Atrévete-te-te|Calle 13|Calle 13|2005",
      "Quiero bailar|Ivy Queen|Diva|2003",
      "Lo siento BB:/|Tainy, Bad Bunny y Julieta Venegas|Data|2021",
      "No me conoce (remix)|Jhay Cortez, J Balvin y Bad Bunny|Famouz|2019",
      "Ateo|C. Tangana y Nathy Peluso|Ateo|2021",
      "Tú me dejaste de querer|C. Tangana, Niño de Elche y La Húngara|El madrileño|2020",
      "Otra vez|Zion & Lennox y J Balvin|Motivan2|2016",
      "Me rehúso|Danny Ocean|54+1|2016",
      "Reggaetón lento (Bailemos)|CNCO|Primera cita|2016",
      "Yo no sé mañana|Luis Enrique|Ciclos|2009",
      "Envolver|Anitta|Versions of Me|2021",
      "Qué hiciste|Jennifer Lopez|Como ama una mujer|2007",
      "Columbia|Quevedo|Donde quiero estar|2023",
      "Playa del Inglés|Quevedo y Myke Towers|Donde quiero estar|2022",
      "Corazón valiente|Gilda|Corazón valiente|1995",
      "Se me ha perdido un corazón|Gilda|Corazón valiente|1995",
      "Fuiste|Gilda||1995",
      "Amor clasificado|Rodrigo|A 2000|2000",
      "Se te ve la tanga|Damas Gratis|Para los pibes|2000",
      "Llegamos los Pibes Chorros|Pibes Chorros|Llegamos los Pibes Chorros|2001",
      "Tirate un paso|Los Wachiturros||2011",
      "L-Gante: Bzrp Music Sessions, Vol. 38|Bizarrap y L-Gante|L-Gante: Bzrp Music Sessions, Vol. 38|2021",
      "La morocha|Luck Ra y BM|La morocha|2023",
      "Hola perdida|Luck Ra y Khea|Hola perdida|2024",
      "Nunca es suficiente|Los Ángeles Azules y Natalia Lafourcade||2018",
      "Cumbia sobre el río|Celso Piña|Barrio bravo|2001",
      "Como la flor|Selena|Entre a mi mundo|1992",
      "Baila esta cumbia|Selena|Ven conmigo|1990",
      "Bidi bidi bom bom|Selena|Amor prohibido|1994",
      "Amor prohibido|Selena|Amor prohibido|1994",
    ] },
    espanol: { name: "Pop y rock en español", ic: "🎤", color: "#b48cff", songs: [
      "Hoy no me puedo levantar|Mecano|Mecano|1981",
      "Cruz de navajas|Mecano|Entre el cielo y el suelo|1986",
      "Mujer contra mujer|Mecano|Descanso dominical|1988",
      "La fuerza del destino|Mecano|Descanso dominical|1988",
      "Hawaii-Bombay|Mecano|Ya viene el sol|1984",
      "Devuélveme a mi chica|Hombres G|Hombres G|1985",
      "Venecia|Hombres G|Hombres G|1985",
      "Marta tiene un marcapasos|Hombres G|Hombres G|1985",
      "Visite nuestro bar|Hombres G|La cagaste... Burt Lancaster|1986",
      "Entre dos tierras|Héroes del Silencio|Senderos de traición|1990",
      "Maldito duende|Héroes del Silencio|Senderos de traición|1990",
      "La chispa adecuada (Bendecida 2)|Héroes del Silencio|Avalancha|1995",
      "Mar adentro|Héroes del Silencio|El mar no cesa|1988",
      "El baile de los que sobran|Los Prisioneros|Pateando piedras|1986",
      "Tren al sur|Los Prisioneros|Corazones|1990",
      "We Are Sudamerican Rockers|Los Prisioneros|La voz de los '80|1984",
      "Muevan las industrias|Los Prisioneros|La cultura de la basura|1987",
      "Estrechez de corazón|Los Prisioneros|Corazones|1990",
      "El duelo|La Ley|Invisible|1995",
      "Aquí|La Ley|Uno|2000",
      "Mentira|La Ley|Uno|2000",
      "La ingrata|Café Tacvba|Re|1994",
      "Las flores|Café Tacvba|Re|1994",
      "Eres|Café Tacvba|Cuatro caminos|2003",
      "Chilanga banda|Café Tacvba|Avalancha de éxitos|1996",
      "María|Café Tacvba|Café Tacvba|1992",
      "Afuera|Caifanes|El nervio del volcán|1994",
      "No dejes que...|Caifanes|El diablito|1990",
      "La célula que explota|Caifanes|El diablito|1990",
      "Viento|Caifanes|Caifanes|1988",
      "En el muelle de San Blas|Maná|Sueños líquidos|1997",
      "Vivir sin aire|Maná|¿Dónde jugarán los niños?|1992",
      "Labios compartidos|Maná|Amar es combatir|2006",
      "Mariposa traicionera|Maná|Revolución de amor|2002",
      "Gimme the Power|Molotov|¿Dónde jugarán las niñas?|1997",
      "Puto|Molotov|¿Dónde jugarán las niñas?|1997",
      "Frijolero|Molotov|Dance and Dense Denso|2003",
      "Triste canción|El Tri|Simplemente|1984",
      "Llueve sobre la ciudad|Los Bunkers|La culpa|2003",
      "Ven aquí|Los Bunkers|Vida de perros|2005",
      "Bolero falaz|Aterciopelados|El Dorado|1995",
      "Florecita rockera|Aterciopelados|El Dorado|1995",
      "Y, ¿si fuera ella?|Alejandro Sanz|Más|1997",
      "Amiga mía|Alejandro Sanz|Más|1997",
      "Cuando nadie me ve|Alejandro Sanz|El alma al aire|2000",
      "El alma al aire|Alejandro Sanz|El alma al aire|2000",
      "Los dos cogidos de la mano|Alejandro Sanz|Viviendo deprisa|1991",
      "Amante bandido|Miguel Bosé|Bandido|1984",
      "Morena mía|Miguel Bosé|Por vos muero|2004",
      "Si tú no vuelves|Miguel Bosé|Bajo el signo de Caín|1993",
      "La soledad|Laura Pausini|Laura Pausini|1994",
      "Se fue|Laura Pausini|Laura Pausini|1994",
      "Víveme|Laura Pausini|Escucha|2004",
      "La incondicional|Luis Miguel|Busca una mujer|1988",
      "Tengo todo excepto a ti|Luis Miguel|20 años|1990",
      "Querida|Juan Gabriel|Recuerdos, Vol. II|1984",
      "Hasta que te conocí|Juan Gabriel|Pensamientos|1986",
      "No tengo dinero|Juan Gabriel|El alma joven|1971",
      "Como tu mujer|Rocío Dúrcal|Como tu mujer|1988",
      "Soy un truhán, soy un señor|Julio Iglesias|Emociones|1978",
      "Hey!|Julio Iglesias|Hey!|1980",
      "Rosas|La Oreja de Van Gogh|Lo que te conté mientras te hacías la dormida|2003",
      "Puedes contar conmigo|La Oreja de Van Gogh|Lo que te conté mientras te hacías la dormida|2003",
      "Cuídate|La Oreja de Van Gogh|Dile al sol|1998",
      "La playa|La Oreja de Van Gogh|El viaje de Copperpot|2000",
      "20 de enero|La Oreja de Van Gogh|El viaje de Copperpot|2000",
      "Zapatillas|El Canto del Loco|Zapatillas|2005",
      "Volverá|El Canto del Loco|Personas|2008",
      "Como Camarón|Estopa|Estopa|1999",
      "La raja de tu falda|Estopa|Estopa|1999",
      "Tu calorro|Estopa|Estopa|1999",
      "Vino tinto|Estopa|Destrangis|2001",
      "Soldadito marinero|Fito & Fitipaldis|Lo más lejos a tu lado|2003",
      "Por la boca vive el pez|Fito & Fitipaldis|Por la boca vive el pez|2006",
      "Antes de que cuente diez|Fito & Fitipaldis|Antes de que cuente diez|2009",
      "Estrella polar|Pereza|Aproximaciones|2007",
      "Sin ti no soy nada|Amaral|Estrella de mar|2002",
      "Como hablar|Amaral|Estrella de mar|2002",
      "Marta, Sebas, Guille y los demás|Amaral|Una pequeña parte del mundo|2000",
      "El universo sobre mí|Amaral|Pájaros en la cabeza|2005",
      "Copenhague|Vetusta Morla|Un día en el mundo|2008",
      "¡Corre!|Jesse & Joy|¿Con quién se queda el perro?|2011",
      "Espacio sideral|Jesse & Joy|Esta es mi vida|2006",
      "Yo quisiera|Reik|Reik|2005",
      "Noviembre sin ti|Reik|Reik|2005",
      "Entra en mi vida|Sin Bandera|Sin Bandera|2002",
      "Kilómetros|Sin Bandera|Sin Bandera|2002",
      "Que lloro|Sin Bandera|De viaje|2003",
      "Todo cambió|Camila|Todo cambió|2006",
      "Abrázame|Camila|Todo cambió|2006",
      "Mientes|Camila|Dejarte de amar|2010",
      "Sin despertar|Kudai|Vuelo|2004",
      "Ni freud ni tu mamá|Belinda|Utopía|2006",
      "Bella traición|Belinda|Utopía|2006",
      "Ángel|Belinda|Belinda|2003",
      "Rebelde|RBD|Rebelde|2004",
      "Sálvame|RBD|Rebelde|2004",
      "Solo quédate en silencio|RBD|Rebelde|2004",
      "Lo aprendí de ti|Ha*Ash|A tiempo|2011",
      "En el 2000|Natalia Lafourcade|Natalia Lafourcade|2002",
      "Hasta la raíz|Natalia Lafourcade|Hasta la raíz|2015",
      "Tú sí sabes quererme|Natalia Lafourcade|Musas|2017",
      "Me voy|Julieta Venegas|Limón y sal|2006",
      "Limón y sal|Julieta Venegas|Limón y sal|2006",
      "Andar conmigo|Julieta Venegas|Sí|2003",
      "Lento|Julieta Venegas|Sí|2003",
      "Tu falta de querer|Mon Laferte|Mon Laferte, Vol. 1|2015",
      "Amor completo|Mon Laferte|Mon Laferte, Vol. 1|2015",
      "Antes de ti|Mon Laferte|Norma|2018",
      "Cómo te atreves|Morat|Sobre el amor y sus efectos secundarios|2016",
      "Mi nuevo vicio|Morat y Paulina Rubio|Sobre el amor y sus efectos secundarios|2015",
      "Besos en guerra|Morat y Juanes|Balas perdidas|2018",
      "Solamente tú|Pablo Alborán|Pablo Alborán|2011",
      "Te he echado de menos|Pablo Alborán|Tanto|2012",
      "Saturno|Pablo Alborán|Prometo|2017",
      "Colgando en tus manos|Carlos Baute y Marta Sánchez|De mi puño y letra|2008",
      "No basta|Franco de Vita|Extranjero|1990",
      "Historia de taxi|Ricardo Arjona|Historias|1994",
      "Señora de las cuatro décadas|Ricardo Arjona|Historias|1994",
      "Si el norte fuera el sur|Ricardo Arjona|Si el norte fuera el sur|1996",
      "El problema|Ricardo Arjona|Santo pecado|2002",
      "A las nueve|No Te Va Gustar|Por lo menos hoy|2006",
      "Todo se transforma|Jorge Drexler|Eco|2004",
      "Movimiento|Jorge Drexler|Salvavidas de hielo|2017",
      "Escuela de calor|Radio Futura|La ley del desierto / La ley del mar|1984",
      "Enamorado de la moda juvenil|Radio Futura|Música moderna|1980",
      "¿A quién le importa?|Alaska y Dinarama|No es pecado|1986",
      "Ni tú ni nadie|Alaska y Dinarama|Deseo carnal|1984",
      "En algún lugar|Duncan Dhu|El grito del tiempo|1987",
      "Déjame|Los Secretos|Los Secretos|1981",
      "20 de abril|Celtas Cortos|Cuéntame un cuento|1991",
      "Lobo hombre en París|La Unión|Mil siluetas|1984",
      "19 días y 500 noches|Joaquín Sabina|19 días y 500 noches|1999",
      "Y nos dieron las diez|Joaquín Sabina|Física y química|1992",
      "Mediterráneo|Joan Manuel Serrat|Mediterráneo|1971",
      "Resistiré|Dúo Dinámico|En forma|1988",
      "Desesperada|Marta Sánchez|Mujer|1993",
      "El talismán|Rosana|Lunas rotas|1996",
      "Sobreviviré|Mónica Naranjo|Minage|2000",
      "Desátame|Mónica Naranjo|Palabra de mujer|1997",
      "Ave María|David Bisbal|Corazón latino|2002",
      "Bulería|David Bisbal|Bulería|2004",
      "Malo|Bebe|Pafuera telarañas|2004",
      "Me gustas tú|Manu Chao|Próxima estación: Esperanza|2001",
      "Clandestino|Manu Chao|Clandestino|1998",
      "Fiesta pagana|Mägo de Oz|Finisterra|2000",
      "La costa del silencio|Mägo de Oz|Gaia|2003",
      "So payaso|Extremoduro|Agíla|1996",
      "Me dediqué a perderte|Alejandro Fernández|A corazón abierto|2004",
      "Pelo suelto|Gloria Trevi|Tu ángel de la guarda|1991",
      "Media naranja|Fey|Fey|1995",
      "Nunca te olvidaré|Enrique Iglesias|Cosas del amor|1998",
      "Ciega, sordomuda|Shakira|¿Dónde están los ladrones?|1998",
      "Pies descalzos, sueños blancos|Shakira|Pies descalzos|1995",
      "Azul|Cristian Castro|Azul|2001",
      "No me doy por vencido|Luis Fonsi|Palabras del silencio|2008",
      "Mi primer millón|Bacilos|Caraluna|2002",
      "Caraluna|Bacilos|Caraluna|2002",
      "Labios rotos|Zoé|Memo Rex Commander y el corazón atómico de la Vía Láctea|2006",
      "Soñé|Zoé|Rocanlover|2003",
      "Disculpa los malos pensamientos|Panda|Para ti con desprecio|2005",
      "El sol no regresa|La Quinta Estación|Flores de alquiler|2004",
      "Algo más|La Quinta Estación|Flores de alquiler|2004",
      "Cannabis|Ska-P|El vals del obrero|1996",
      "Lo echamos a suertes|Ella Baila Sola|Ella Baila Sola|1996",
      "Camino Soria|Gabinete Caligari|Camino Soria|1987",
      "Insurrección|El Último de la Fila|Enemigos de lo ajeno|1986",
      "Como un burro amarrado en la puerta del baile|El Último de la Fila|Como la cabeza al sombrero|1988",
      "Bienvenidos|Miguel Ríos|Rocanrol bumerang|1980",
      "Los rockeros van al infierno|Barón Rojo|Volumen brutal|1982",
      "Cuando respiro en tu boca|Lucybell|Lumina|2004",
      "La espada & la pared|Los Tres|La espada & la pared|1995",
      "El hombre que yo amo|Myriam Hernández|Myriam Hernández|1988",
      "Va a escampar|La Vela Puerca|A contraluz|2004",
      "El viejo|La Vela Puerca|De bichos y flores|2001",
      "Depende|Jarabe de Palo|Depende|1998",
      "Carolina|M-Clan|Usar y tirar|1999",
      "Vidas paralelas|Ximena Sariñana|Mediocre|2008",
      "Rosa pastel|Belanova|Dulce beat|2005",
      "El triste|José José|El triste|1970",
      "Un beso y una flor|Nino Bravo|Un beso y una flor|1972",
    ] },
    clasicos: { name: "Clásicos en inglés", ic: "📼", color: "#4fd1ff", songs: [
      "Billie Jean|Michael Jackson|Thriller|1982",
      "Thriller|Michael Jackson|Thriller|1982",
      "Beat It|Michael Jackson|Thriller|1982",
      "Black or White|Michael Jackson|Dangerous|1991",
      "Bohemian Rhapsody|Queen|A Night at the Opera|1975",
      "Don't Stop Me Now|Queen|Jazz|1978",
      "Another One Bites the Dust|Queen|The Game|1980",
      "Under Pressure|Queen y David Bowie|Hot Space|1981",
      "Like a Prayer|Madonna|Like a Prayer|1989",
      "Like a Virgin|Madonna|Like a Virgin|1984",
      "Material Girl|Madonna|Like a Virgin|1984",
      "Vogue|Madonna|I'm Breathless|1990",
      "Smells Like Teen Spirit|Nirvana|Nevermind|1991",
      "Sweet Child O' Mine|Guns N' Roses|Appetite for Destruction|1987",
      "Hotel California|Eagles|Hotel California|1976",
      "Imagine|John Lennon|Imagine|1971",
      "Let It Be|The Beatles|Let It Be|1970",
      "Here Comes the Sun|The Beatles|Abbey Road|1969",
      "Yesterday|The Beatles|Help!|1965",
      "(I Can't Get No) Satisfaction|The Rolling Stones|Out of Our Heads|1965",
      "Like a Rolling Stone|Bob Dylan|Highway 61 Revisited|1965",
      "Respect|Aretha Franklin|I Never Loved a Man the Way I Love You|1967",
      "Wonderwall|Oasis|(What's the Story) Morning Glory?|1995",
      "With or Without You|U2|The Joshua Tree|1987",
      "Every Breath You Take|The Police|Synchronicity|1983",
      "Take On Me|a-ha|Hunting High and Low|1985",
      "Livin' on a Prayer|Bon Jovi|Slippery When Wet|1986",
      "Africa|Toto|Toto IV|1982",
      "Girls Just Want to Have Fun|Cyndi Lauper|She's So Unusual|1983",
      "Time After Time|Cyndi Lauper|She's So Unusual|1984",
      "I Will Survive|Gloria Gaynor|Love Tracks|1978",
      "Stayin' Alive|Bee Gees|Saturday Night Fever|1977",
      "Dancing Queen|ABBA|Arrival|1976",
      "Le Freak|Chic|C'est Chic|1978",
      "Y.M.C.A.|Village People|Cruisin'|1978",
      "Wannabe|Spice Girls|Spice|1996",
      "...Baby One More Time|Britney Spears|...Baby One More Time|1998",
      "I Want It That Way|Backstreet Boys|Millennium|1999",
      "Smooth|Santana y Rob Thomas|Supernatural|1999",
      "Zombie|The Cranberries|No Need to Argue|1994",
      "Losing My Religion|R.E.M.|Out of Time|1991",
      "Creep|Radiohead|Pablo Honey|1992",
      "Wish You Were Here|Pink Floyd|Wish You Were Here|1975",
      "Another Brick in the Wall (Part 2)|Pink Floyd|The Wall|1979",
      "Highway to Hell|AC/DC|Highway to Hell|1979",
      "Back in Black|AC/DC|Back in Black|1980",
      "Enter Sandman|Metallica|Metallica|1991",
      "Nothing Else Matters|Metallica|Metallica|1991",
      "Sweet Dreams (Are Made of This)|Eurythmics|Sweet Dreams (Are Made of This)|1983",
      "Total Eclipse of the Heart|Bonnie Tyler|Faster Than the Speed of Night|1983",
      "Never Gonna Give You Up|Rick Astley|Whenever You Need Somebody|1987",
      "Purple Rain|Prince|Purple Rain|1984",
      "Kiss|Prince|Parade|1986",
      "Don't Stop Believin'|Journey|Escape|1981",
      "Eye of the Tiger|Survivor|Eye of the Tiger|1982",
      "Born in the U.S.A.|Bruce Springsteen|Born in the U.S.A.|1984",
      "Jump|Van Halen|1984|1984",
      "I Will Always Love You|Whitney Houston|The Bodyguard|1992",
      "My Heart Will Go On|Céline Dion|Let's Talk About Love|1997",
      "Torn|Natalie Imbruglia|Left of the Middle|1997",
      "Hey Jude|The Beatles|Hey Jude|1968",
      "Twist and Shout|The Beatles|Please Please Me|1963",
      "Help!|The Beatles|Help!|1965",
      "Come Together|The Beatles|Abbey Road|1969",
      "Paint It Black|The Rolling Stones|Aftermath|1966",
      "Start Me Up|The Rolling Stones|Tattoo You|1981",
      "Sympathy for the Devil|The Rolling Stones|Beggars Banquet|1968",
      "Angie|The Rolling Stones|Goats Head Soup|1973",
      "We Will Rock You|Queen|News of the World|1977",
      "We Are the Champions|Queen|News of the World|1977",
      "Radio Ga Ga|Queen|The Works|1984",
      "I Want to Break Free|Queen|The Works|1984",
      "Somebody to Love|Queen|A Day at the Races|1976",
      "Smooth Criminal|Michael Jackson|Bad|1987",
      "Bad|Michael Jackson|Bad|1987",
      "Man in the Mirror|Michael Jackson|Bad|1987",
      "Don't Stop 'Til You Get Enough|Michael Jackson|Off the Wall|1979",
      "Rock with You|Michael Jackson|Off the Wall|1979",
      "La Isla Bonita|Madonna|True Blue|1986",
      "Papa Don't Preach|Madonna|True Blue|1986",
      "Holiday|Madonna|Madonna|1983",
      "Frozen|Madonna|Ray of Light|1998",
      "Ray of Light|Madonna|Ray of Light|1998",
      "Come as You Are|Nirvana|Nevermind|1991",
      "Lithium|Nirvana|Nevermind|1991",
      "Heart-Shaped Box|Nirvana|In Utero|1993",
      "Welcome to the Jungle|Guns N' Roses|Appetite for Destruction|1987",
      "Paradise City|Guns N' Roses|Appetite for Destruction|1987",
      "November Rain|Guns N' Roses|Use Your Illusion I|1991",
      "Knockin' on Heaven's Door|Bob Dylan|Pat Garrett & Billy the Kid|1973",
      "Blowin' in the Wind|Bob Dylan|The Freewheelin' Bob Dylan|1963",
      "Don't Look Back in Anger|Oasis|(What's the Story) Morning Glory?|1995",
      "Live Forever|Oasis|Definitely Maybe|1994",
      "One|U2|Achtung Baby|1991",
      "Sunday Bloody Sunday|U2|War|1983",
      "I Still Haven't Found What I'm Looking For|U2|The Joshua Tree|1987",
      "Where the Streets Have No Name|U2|The Joshua Tree|1987",
      "Roxanne|The Police|Outlandos d'Amour|1978",
      "Message in a Bottle|The Police|Reggatta de Blanc|1979",
      "Every Little Thing She Does Is Magic|The Police|Ghost in the Machine|1981",
      "Fields of Gold|Sting|Ten Summoner's Tales|1993",
      "Englishman in New York|Sting|...Nothing Like the Sun|1987",
      "You Give Love a Bad Name|Bon Jovi|Slippery When Wet|1986",
      "Always|Bon Jovi|Cross Road|1994",
      "Bed of Roses|Bon Jovi|Keep the Faith|1993",
      "Hold the Line|Toto|Toto|1978",
      "Rosanna|Toto|Toto IV|1982",
      "True Colors|Cyndi Lauper|True Colors|1986",
      "Night Fever|Bee Gees|Saturday Night Fever|1977",
      "How Deep Is Your Love|Bee Gees|Saturday Night Fever|1977",
      "Tragedy|Bee Gees|Spirits Having Flown|1979",
      "Mamma Mia|ABBA|ABBA|1975",
      "Waterloo|ABBA|Waterloo|1974",
      "Take a Chance on Me|ABBA|The Album|1977",
      "The Winner Takes It All|ABBA|Super Trouper|1980",
      "Good Times|Chic|Risqué|1979",
      "In the Navy|Village People|Go West|1979",
      "Macho Man|Village People|Macho Man|1978",
      "Spice Up Your Life|Spice Girls|Spiceworld|1997",
      "Say You'll Be There|Spice Girls|Spice|1996",
      "Sometimes|Britney Spears|...Baby One More Time|1999",
      "Everybody (Backstreet's Back)|Backstreet Boys|Backstreet's Back|1997",
      "As Long as You Love Me|Backstreet Boys|Backstreet's Back|1997",
      "Quit Playin' Games (With My Heart)|Backstreet Boys|Backstreet Boys|1996",
      "Linger|The Cranberries|Everybody Else Is Doing It, So Why Can't We?|1993",
      "Dreams|The Cranberries|Everybody Else Is Doing It, So Why Can't We?|1992",
      "Everybody Hurts|R.E.M.|Automatic for the People|1992",
      "Shiny Happy People|R.E.M.|Out of Time|1991",
      "Karma Police|Radiohead|OK Computer|1997",
      "High and Dry|Radiohead|The Bends|1995",
      "Money|Pink Floyd|The Dark Side of the Moon|1973",
      "Comfortably Numb|Pink Floyd|The Wall|1979",
      "Thunderstruck|AC/DC|The Razors Edge|1990",
      "You Shook Me All Night Long|AC/DC|Back in Black|1980",
      "The Unforgiven|Metallica|Metallica|1991",
      "Here Comes the Rain Again|Eurythmics|Touch|1983",
      "Holding Out for a Hero|Bonnie Tyler|Footloose|1984",
      "Together Forever|Rick Astley|Whenever You Need Somebody|1987",
      "When Doves Cry|Prince|Purple Rain|1984",
      "1999|Prince|1999|1982",
      "Separate Ways (Worlds Apart)|Journey|Frontiers|1983",
      "Open Arms|Journey|Escape|1981",
      "Dancing in the Dark|Bruce Springsteen|Born in the U.S.A.|1984",
      "Streets of Philadelphia|Bruce Springsteen|Philadelphia|1994",
      "Panama|Van Halen|1984|1984",
      "I Wanna Dance with Somebody (Who Loves Me)|Whitney Houston|Whitney|1987",
      "Greatest Love of All|Whitney Houston|Whitney Houston|1985",
      "I Have Nothing|Whitney Houston|The Bodyguard|1992",
      "Because You Loved Me|Céline Dion|Falling into You|1996",
      "Superstition|Stevie Wonder|Talking Book|1972",
      "I Just Called to Say I Love You|Stevie Wonder|The Woman in Red|1984",
      "Sir Duke|Stevie Wonder|Songs in the Key of Life|1976",
      "Isn't She Lovely|Stevie Wonder|Songs in the Key of Life|1976",
      "September|Earth, Wind & Fire|The Best of Earth, Wind & Fire, Vol. 1|1978",
      "Boogie Wonderland|Earth, Wind & Fire y The Emotions|I Am|1979",
      "Let's Groove|Earth, Wind & Fire|Raise!|1981",
      "Celebration|Kool & the Gang|Celebrate!|1980",
      "Get Down on It|Kool & the Gang|Something Special|1981",
      "Ain't No Mountain High Enough|Marvin Gaye y Tammi Terrell|United|1967",
      "I Heard It Through the Grapevine|Marvin Gaye|In the Groove|1968",
      "Sexual Healing|Marvin Gaye|Midnight Love|1982",
      "Let's Get It On|Marvin Gaye|Let's Get It On|1973",
      "Stand by Me|Ben E. King|Don't Play That Song!|1961",
      "What a Wonderful World|Louis Armstrong|What a Wonderful World|1967",
      "(Sittin' On) The Dock of the Bay|Otis Redding|The Dock of the Bay|1968",
      "Proud Mary|Creedence Clearwater Revival|Bayou Country|1969",
      "Have You Ever Seen the Rain|Creedence Clearwater Revival|Pendulum|1970",
      "Bad Moon Rising|Creedence Clearwater Revival|Green River|1969",
      "Fortunate Son|Creedence Clearwater Revival|Willy and the Poor Boys|1969",
      "Light My Fire|The Doors|The Doors|1967",
      "Riders on the Storm|The Doors|L.A. Woman|1971",
      "Born to Be Wild|Steppenwolf|Steppenwolf|1968",
      "California Dreamin'|The Mamas & the Papas|If You Can Believe Your Eyes and Ears|1965",
      "Surfin' U.S.A.|The Beach Boys|Surfin' U.S.A.|1963",
      "Wouldn't It Be Nice|The Beach Boys|Pet Sounds|1966",
      "Bridge over Troubled Water|Simon & Garfunkel|Bridge over Troubled Water|1970",
      "Can't Help Falling in Love|Elvis Presley|Blue Hawaii|1961",
      "Suspicious Minds|Elvis Presley|Suspicious Minds|1969",
      "Your Song|Elton John|Elton John|1970",
      "Rocket Man|Elton John|Honky Château|1972",
      "I'm Still Standing|Elton John|Too Low for Zero|1983",
      "Can You Feel the Love Tonight|Elton John|The Lion King|1994",
      "Heroes|David Bowie|Heroes|1977",
      "Let's Dance|David Bowie|Let's Dance|1983",
      "Starman|David Bowie|The Rise and Fall of Ziggy Stardust and the Spiders from Mars|1972",
      "Stairway to Heaven|Led Zeppelin|Led Zeppelin IV|1971",
      "Whole Lotta Love|Led Zeppelin|Led Zeppelin II|1969",
      "Smoke on the Water|Deep Purple|Machine Head|1972",
      "Paranoid|Black Sabbath|Paranoid|1970",
      "Dream On|Aerosmith|Aerosmith|1973",
      "I Don't Want to Miss a Thing|Aerosmith|Armageddon: The Album|1998",
      "Crazy|Aerosmith|Get a Grip|1993",
      "Rock and Roll All Nite|Kiss|Dressed to Kill|1975",
      "I Was Made for Lovin' You|Kiss|Dynasty|1979",
      "The Final Countdown|Europe|The Final Countdown|1986",
      "Pour Some Sugar on Me|Def Leppard|Hysteria|1987",
      "Still Loving You|Scorpions|Love at First Sting|1984",
      "Wind of Change|Scorpions|Crazy World|1990",
      "Rock You Like a Hurricane|Scorpions|Love at First Sting|1984",
      "Summer of '69|Bryan Adams|Reckless|1984",
      "(Everything I Do) I Do It for You|Bryan Adams|Robin Hood: Prince of Thieves|1991",
      "Hungry Like the Wolf|Duran Duran|Rio|1982",
      "Rio|Duran Duran|Rio|1982",
      "Just Can't Get Enough|Depeche Mode|Speak & Spell|1981",
      "Enjoy the Silence|Depeche Mode|Violator|1990",
      "Personal Jesus|Depeche Mode|Violator|1989",
      "Just Like Heaven|The Cure|Kiss Me, Kiss Me, Kiss Me|1987",
      "Friday I'm in Love|The Cure|Wish|1992",
      "Don't You (Forget About Me)|Simple Minds|The Breakfast Club|1985",
      "Tainted Love|Soft Cell|Non-Stop Erotic Cabaret|1981",
      "Blue Monday|New Order|Blue Monday|1983",
      "Don't You Want Me|The Human League|Dare|1981",
      "Relax|Frankie Goes to Hollywood|Welcome to the Pleasuredome|1983",
      "Wake Me Up Before You Go-Go|Wham!|Make It Big|1984",
      "Careless Whisper|George Michael|Make It Big|1984",
      "Faith|George Michael|Faith|1987",
      "Freedom! '90|George Michael|Listen Without Prejudice Vol. 1|1990",
      "Tarzan Boy|Baltimora|Living in the Background|1985",
      "Self Control|Laura Branigan|Self Control|1984",
      "Gloria|Laura Branigan|Branigan|1982",
      "Flashdance... What a Feeling|Irene Cara|Flashdance|1983",
      "Maniac|Michael Sembello|Flashdance|1983",
      "Footloose|Kenny Loggins|Footloose|1984",
      "Danger Zone|Kenny Loggins|Top Gun|1986",
      "Take My Breath Away|Berlin|Top Gun|1986",
      "Ghostbusters|Ray Parker Jr.|Ghostbusters|1984",
      "The Power of Love|Huey Lewis and the News|Back to the Future|1985",
      "Don't Worry, Be Happy|Bobby McFerrin|Simple Pleasures|1988",
      "Walk Like an Egyptian|The Bangles|Different Light|1986",
      "Eternal Flame|The Bangles|Everything|1988",
      "Everybody Wants to Rule the World|Tears for Fears|Songs from the Big Chair|1985",
      "Shout|Tears for Fears|Songs from the Big Chair|1984",
      "Need You Tonight|INXS|Kick|1987",
      "Owner of a Lonely Heart|Yes|90125|1983",
      "In the Air Tonight|Phil Collins|Face Value|1981",
      "Another Day in Paradise|Phil Collins|...But Seriously|1989",
      "Invisible Touch|Genesis|Invisible Touch|1986",
      "Uptown Girl|Billy Joel|An Innocent Man|1983",
      "Piano Man|Billy Joel|Piano Man|1973",
      "Hello|Lionel Richie|Can't Slow Down|1983",
      "All Night Long (All Night)|Lionel Richie|Can't Slow Down|1983",
      "We Are the World|USA for Africa|We Are the World|1985",
      "Physical|Olivia Newton-John|Physical|1981",
      "You're the One That I Want|John Travolta y Olivia Newton-John|Grease|1978",
      "Summer Nights|John Travolta y Olivia Newton-John|Grease|1978",
      "I'm So Excited|The Pointer Sisters|So Excited!|1982",
      "Hot Stuff|Donna Summer|Bad Girls|1979",
      "I Feel Love|Donna Summer|I Remember Yesterday|1977",
      "Rasputin|Boney M.|Nightflight to Venus|1978",
      "Daddy Cool|Boney M.|Take the Heat off Me|1976",
      "Rivers of Babylon|Boney M.|Nightflight to Venus|1978",
      "Ring My Bell|Anita Ward|Songs of Love|1979",
      "Kung Fu Fighting|Carl Douglas|Kung Fu Fighting and Other Love Songs|1974",
      "That's the Way (I Like It)|KC and the Sunshine Band|KC and the Sunshine Band|1975",
      "Lady Marmalade|Labelle|Nightbirds|1974",
      "Super Freak|Rick James|Street Songs|1981",
      "Play That Funky Music|Wild Cherry|Wild Cherry|1976",
      "Disco Inferno|The Trammps|Disco Inferno|1976",
      "Gonna Make You Sweat (Everybody Dance Now)|C+C Music Factory|Gonna Make You Sweat|1990",
      "Rhythm Is a Dancer|Snap!|The Madman's Return|1992",
      "The Power|Snap!|World Power|1990",
      "What Is Love|Haddaway|The Album|1993",
      "Mr. Vain|Culture Beat|Serenity|1993",
      "No Limit|2 Unlimited|No Limits!|1993",
      "The Rhythm of the Night|Corona|The Rhythm of the Night|1993",
      "Be My Lover|La Bouche|Sweet Dreams|1995",
      "Blue (Da Ba Dee)|Eiffel 65|Europop|1998",
      "Barbie Girl|Aqua|Aquarium|1997",
      "Cotton Eye Joe|Rednex|Sex & Violins|1994",
      "Freed from Desire|Gala|Come into My Life|1996",
      "Children|Robert Miles|Dreamland|1995",
      "Pump Up the Jam|Technotronic|Pump Up the Jam: The Album|1989",
      "Mambo No. 5 (A Little Bit of...)|Lou Bega|A Little Bit of Mambo|1999",
      "Believe|Cher|Believe|1998",
      "Gangsta's Paradise|Coolio y L.V.|Dangerous Minds|1995",
      "U Can't Touch This|MC Hammer|Please Hammer, Don't Hurt 'Em|1990",
      "Killing Me Softly with His Song|Fugees|The Score|1996",
      "No Scrubs|TLC|FanMail|1999",
      "Waterfalls|TLC|CrazySexyCool|1995",
      "Hero|Mariah Carey|Music Box|1993",
      "Fantasy|Mariah Carey|Daydream|1995",
      "Truly Madly Deeply|Savage Garden|Savage Garden|1997",
      "I Want You|Savage Garden|Savage Garden|1996",
      "Kiss from a Rose|Seal|Seal|1994",
      "Iris|Goo Goo Dolls|City of Angels|1998",
      "Ironic|Alanis Morissette|Jagged Little Pill|1995",
      "You Oughta Know|Alanis Morissette|Jagged Little Pill|1995",
      "Don't Speak|No Doubt|Tragic Kingdom|1995",
      "Bitter Sweet Symphony|The Verve|Urban Hymns|1997",
      "Song 2|Blur|Blur|1997",
      "Girls & Boys|Blur|Parklife|1994",
      "Common People|Pulp|Different Class|1995",
      "Tubthumping|Chumbawamba|Tubthumper|1997",
      "Black Hole Sun|Soundgarden|Superunknown|1994",
      "Under the Bridge|Red Hot Chili Peppers|Blood Sugar Sex Magik|1991",
      "Give It Away|Red Hot Chili Peppers|Blood Sugar Sex Magik|1991",
      "Californication|Red Hot Chili Peppers|Californication|1999",
      "Scar Tissue|Red Hot Chili Peppers|Californication|1999",
      "Alive|Pearl Jam|Ten|1991",
      "Jeremy|Pearl Jam|Ten|1991",
      "Basket Case|Green Day|Dookie|1994",
      "Good Riddance (Time of Your Life)|Green Day|Nimrod|1997",
      "All Star|Smash Mouth|Astro Lounge|1999",
      "Self Esteem|The Offspring|Smash|1994",
      "Pretty Fly (for a White Guy)|The Offspring|Americana|1998",
      "Killing in the Name|Rage Against the Machine|Rage Against the Machine|1992",
      "Bullet with Butterfly Wings|The Smashing Pumpkins|Mellon Collie and the Infinite Sadness|1995",
      "Kiss Me|Sixpence None the Richer|Sixpence None the Richer|1997",
      "MMMBop|Hanson|Middle of Nowhere|1997",
      "Lovefool|The Cardigans|First Band on the Moon|1996",
      "Back for Good|Take That|Nobody Else|1995",
      "Angels|Robbie Williams|Life thru a Lens|1997",
      "Genie in a Bottle|Christina Aguilera|Christina Aguilera|1999",
      "My Way|Frank Sinatra|My Way|1969",
      "Ain't No Sunshine|Bill Withers|Just As I Am|1971",
      "Lean on Me|Bill Withers|Still Bill|1972",
      "Let's Stay Together|Al Green|Let's Stay Together|1971",
      "Think|Aretha Franklin|Aretha Now|1968",
      "(You Make Me Feel Like) A Natural Woman|Aretha Franklin|Lady Soul|1967",
      "Dust in the Wind|Kansas|Point of Know Return|1977",
      "More Than a Feeling|Boston|Boston|1976",
      "Go Your Own Way|Fleetwood Mac|Rumours|1977",
      "Everywhere|Fleetwood Mac|Tango in the Night|1987",
      "Layla|Derek and the Dominos|Layla and Other Assorted Love Songs|1970",
      "Wonderful Tonight|Eric Clapton|Slowhand|1977",
      "Tears in Heaven|Eric Clapton|Rush|1992",
      "Sweet Home Alabama|Lynyrd Skynyrd|Second Helping|1974",
      "Video Killed the Radio Star|The Buggles|The Age of Plastic|1979",
      "Down Under|Men at Work|Business as Usual|1981",
      "Come On Eileen|Dexys Midnight Runners|Too-Rye-Ay|1982",
      "Karma Chameleon|Culture Club|Colour by Numbers|1983",
      "Gold|Spandau Ballet|True|1983",
      "True|Spandau Ballet|True|1983",
      "Forever Young|Alphaville|Forever Young|1984",
      "Big in Japan|Alphaville|Forever Young|1984",
      "Smalltown Boy|Bronski Beat|The Age of Consent|1984",
      "It's a Sin|Pet Shop Boys|Actually|1987",
      "Go West|Pet Shop Boys|Very|1993",
      "You Spin Me Round (Like a Record)|Dead or Alive|Youthquake|1984",
      "I Ran (So Far Away)|A Flock of Seagulls|A Flock of Seagulls|1982",
      "Venus|Bananarama|True Confessions|1986",
      "Running Up That Hill|Kate Bush|Hounds of Love|1985",
      "Sledgehammer|Peter Gabriel|So|1986",
      "Sultans of Swing|Dire Straits|Dire Straits|1978",
      "Money for Nothing|Dire Straits|Brothers in Arms|1985",
      "Walk of Life|Dire Straits|Brothers in Arms|1985",
      "Don't Dream It's Over|Crowded House|Crowded House|1986",
      "Bette Davis Eyes|Kim Carnes|Mistaken Identity|1981",
      "Smooth Operator|Sade|Diamond Life|1984",
      "I Love Rock 'n' Roll|Joan Jett and the Blackhearts|I Love Rock 'n' Roll|1981",
      "Call Me|Blondie|American Gigolo|1980",
      "Heart of Glass|Blondie|Parallel Lines|1978",
      "Should I Stay or Should I Go|The Clash|Combat Rock|1982",
      "London Calling|The Clash|London Calling|1979",
      "Blitzkrieg Bop|Ramones|Ramones|1976",
      "Once in a Lifetime|Talking Heads|Remain in Light|1980",
      "Rebel Yell|Billy Idol|Rebel Yell|1983",
      "White Wedding|Billy Idol|Billy Idol|1982",
      "I'm a Believer|The Monkees|More of the Monkees|1966",
      "Black Magic Woman|Santana|Abraxas|1970",
      "My Sharona|The Knack|Get the Knack|1979",
      "Walk on the Wild Side|Lou Reed|Transformer|1972",
      "One of Us|Joan Osborne|Relish|1995",
      "What's Up?|4 Non Blondes|Bigger, Better, Faster, More!|1992",
    ] },
    hits: { name: "Hits en inglés 2000+", ic: "🔥", color: "#ffb627", songs: [
      "Crazy in Love|Beyoncé|Dangerously in Love|2003",
      "Halo|Beyoncé|I Am... Sasha Fierce|2008",
      "Single Ladies (Put a Ring on It)|Beyoncé|I Am... Sasha Fierce|2008",
      "Hey Ya!|Outkast|Speakerboxxx/The Love Below|2003",
      "Mr. Brightside|The Killers|Hot Fuss|2004",
      "Seven Nation Army|The White Stripes|Elephant|2003",
      "Umbrella|Rihanna|Good Girl Gone Bad|2007",
      "Diamonds|Rihanna|Unapologetic|2012",
      "We Found Love|Rihanna y Calvin Harris|Talk That Talk|2011",
      "Rolling in the Deep|Adele|21|2010",
      "Someone Like You|Adele|21|2011",
      "Rehab|Amy Winehouse|Back to Black|2006",
      "Uptown Funk|Mark Ronson y Bruno Mars|Uptown Special|2014",
      "Locked Out of Heaven|Bruno Mars|Unorthodox Jukebox|2012",
      "Just the Way You Are|Bruno Mars|Doo-Wops & Hooligans|2010",
      "Shape of You|Ed Sheeran|÷|2017",
      "Thinking Out Loud|Ed Sheeran|x|2014",
      "Blinding Lights|The Weeknd|After Hours|2019",
      "Can't Feel My Face|The Weeknd|Beauty Behind the Madness|2015",
      "Starboy|The Weeknd y Daft Punk|Starboy|2016",
      "Bad Guy|Billie Eilish|When We All Fall Asleep, Where Do We Go?|2019",
      "Happy|Pharrell Williams|Despicable Me 2|2013",
      "Get Lucky|Daft Punk y Pharrell Williams|Random Access Memories|2013",
      "Poker Face|Lady Gaga|The Fame|2008",
      "Just Dance|Lady Gaga|The Fame|2008",
      "Bad Romance|Lady Gaga|The Fame Monster|2009",
      "Shallow|Lady Gaga y Bradley Cooper|A Star Is Born|2018",
      "Viva la Vida|Coldplay|Viva la Vida or Death and All His Friends|2008",
      "Yellow|Coldplay|Parachutes|2000",
      "Clocks|Coldplay|A Rush of Blood to the Head|2002",
      "Numb|Linkin Park|Meteora|2003",
      "In the End|Linkin Park|Hybrid Theory|2000",
      "Somebody That I Used to Know|Gotye|Making Mirrors|2011",
      "Toxic|Britney Spears|In the Zone|2003",
      "Since U Been Gone|Kelly Clarkson|Breakaway|2004",
      "Party Rock Anthem|LMFAO|Sorry for Party Rocking|2011",
      "I Gotta Feeling|The Black Eyed Peas|The E.N.D.|2009",
      "Where Is the Love?|The Black Eyed Peas|Elephunk|2003",
      "Firework|Katy Perry|Teenage Dream|2010",
      "Roar|Katy Perry|Prism|2013",
      "Love Story|Taylor Swift|Fearless|2008",
      "Shake It Off|Taylor Swift|1989|2014",
      "Anti-Hero|Taylor Swift|Midnights|2022",
      "Don't Start Now|Dua Lipa|Future Nostalgia|2019",
      "Levitating|Dua Lipa|Future Nostalgia|2020",
      "As It Was|Harry Styles|Harry's House|2022",
      "drivers license|Olivia Rodrigo|SOUR|2021",
      "Flowers|Miley Cyrus|Endless Summer Vacation|2023",
      "Wrecking Ball|Miley Cyrus|Bangerz|2013",
      "Stay|The Kid LAROI y Justin Bieber|F*ck Love 3: Over You|2021",
      "Sorry|Justin Bieber|Purpose|2015",
      "Counting Stars|OneRepublic|Native|2013",
      "Radioactive|Imagine Dragons|Night Visions|2012",
      "Believer|Imagine Dragons|Evolve|2017",
      "Pumped Up Kicks|Foster the People|Torches|2010",
      "Royals|Lorde|Pure Heroine|2013",
      "Chandelier|Sia|1000 Forms of Fear|2014",
      "Cheap Thrills|Sia|This Is Acting|2016",
      "Lose Yourself|Eminem|8 Mile|2002",
      "Without Me|Eminem|The Eminem Show|2002",
      "The Real Slim Shady|Eminem|The Marshall Mathers LP|2000",
      "Love the Way You Lie|Eminem y Rihanna|Recovery|2010",
      "In da Club|50 Cent|Get Rich or Die Tryin'|2003",
      "Yeah!|Usher y Lil Jon y Ludacris|Confessions|2004",
      "Promiscuous|Nelly Furtado y Timbaland|Loose|2006",
      "Maneater|Nelly Furtado|Loose|2006",
      "I'm Like a Bird|Nelly Furtado|Whoa, Nelly!|2000",
      "SexyBack|Justin Timberlake|FutureSex/LoveSounds|2006",
      "Cry Me a River|Justin Timberlake|Justified|2002",
      "Can't Stop the Feeling!|Justin Timberlake|Trolls (Original Motion Picture Soundtrack)|2016",
      "Only Girl (In the World)|Rihanna|Loud|2010",
      "Don't Stop the Music|Rihanna|Good Girl Gone Bad|2007",
      "Pump It|The Black Eyed Peas|Monkey Business|2005",
      "Boom Boom Pow|The Black Eyed Peas|The E.N.D.|2009",
      "I Kissed a Girl|Katy Perry|One of the Boys|2008",
      "Hot n Cold|Katy Perry|One of the Boys|2008",
      "California Gurls|Katy Perry y Snoop Dogg|Teenage Dream|2010",
      "Dark Horse|Katy Perry y Juicy J|Prism|2013",
      "Telephone|Lady Gaga y Beyoncé|The Fame Monster|2009",
      "Born This Way|Lady Gaga|Born This Way|2011",
      "Oops!... I Did It Again|Britney Spears|Oops!... I Did It Again|2000",
      "Gimme More|Britney Spears|Blackout|2007",
      "Womanizer|Britney Spears|Circus|2008",
      "Beautiful|Christina Aguilera|Stripped|2002",
      "Lady Marmalade|Christina Aguilera y Lil' Kim y Mýa y Pink|Moulin Rouge! Music from Baz Luhrmann's Film|2001",
      "Get the Party Started|Pink|Missundaztood|2001",
      "So What|Pink|Funhouse|2008",
      "Just Give Me a Reason|Pink y Nate Ruess|The Truth About Love|2012",
      "Stronger (What Doesn't Kill You)|Kelly Clarkson|Stronger|2011",
      "Because of You|Kelly Clarkson|Breakaway|2004",
      "Complicated|Avril Lavigne|Let Go|2002",
      "Sk8er Boi|Avril Lavigne|Let Go|2002",
      "Girlfriend|Avril Lavigne|The Best Damn Thing|2007",
      "Fix You|Coldplay|X&Y|2005",
      "A Sky Full of Stars|Coldplay|Ghost Stories|2014",
      "Somebody Told Me|The Killers|Hot Fuss|2004",
      "Human|The Killers|Day & Age|2008",
      "Do I Wanna Know?|Arctic Monkeys|AM|2013",
      "I Bet You Look Good on the Dancefloor|Arctic Monkeys|Whatever People Say I Am, That's What I'm Not|2005",
      "Take Me Out|Franz Ferdinand|Franz Ferdinand|2004",
      "Use Somebody|Kings of Leon|Only by the Night|2008",
      "Sex on Fire|Kings of Leon|Only by the Night|2008",
      "Last Nite|The Strokes|Is This It|2001",
      "Can't Stop|Red Hot Chili Peppers|By the Way|2002",
      "By the Way|Red Hot Chili Peppers|By the Way|2002",
      "Dani California|Red Hot Chili Peppers|Stadium Arcadium|2006",
      "Boulevard of Broken Dreams|Green Day|American Idiot|2004",
      "American Idiot|Green Day|American Idiot|2004",
      "What I've Done|Linkin Park|Minutes to Midnight|2007",
      "Uprising|Muse|The Resistance|2009",
      "Supermassive Black Hole|Muse|Black Holes and Revelations|2006",
      "Best of You|Foo Fighters|In Your Honor|2005",
      "The Pretender|Foo Fighters|Echoes, Silence, Patience & Grace|2007",
      "Chop Suey!|System of a Down|Toxicity|2001",
      "Bring Me to Life|Evanescence|Fallen|2003",
      "This Love|Maroon 5|Songs About Jane|2002",
      "Moves like Jagger|Maroon 5 y Christina Aguilera|Hands All Over|2011",
      "Payphone|Maroon 5 y Wiz Khalifa|Overexposed|2012",
      "Sugar|Maroon 5|V|2014",
      "Grenade|Bruno Mars|Doo-Wops & Hooligans|2010",
      "24K Magic|Bruno Mars|24K Magic|2016",
      "That's What I Like|Bruno Mars|24K Magic|2016",
      "Perfect|Ed Sheeran|÷|2017",
      "Photograph|Ed Sheeran|x|2014",
      "Hello|Adele|25|2015",
      "Set Fire to the Rain|Adele|21|2011",
      "Save Your Tears|The Weeknd|After Hours|2020",
      "The Hills|The Weeknd|Beauty Behind the Madness|2015",
      "New Rules|Dua Lipa|Dua Lipa|2017",
      "Dance the Night|Dua Lipa|Barbie the Album|2023",
      "Houdini|Dua Lipa|Radical Optimism|2023",
      "Watermelon Sugar|Harry Styles|Fine Line|2019",
      "Sign of the Times|Harry Styles|Harry Styles|2017",
      "What Was I Made For?|Billie Eilish|Barbie the Album|2023",
      "Birds of a Feather|Billie Eilish|Hit Me Hard and Soft|2024",
      "Good 4 U|Olivia Rodrigo|SOUR|2021",
      "Vampire|Olivia Rodrigo|GUTS|2023",
      "Blank Space|Taylor Swift|1989|2014",
      "You Belong with Me|Taylor Swift|Fearless|2008",
      "Party in the U.S.A.|Miley Cyrus|The Time of Our Lives|2009",
      "Baby|Justin Bieber y Ludacris|My World 2.0|2010",
      "Love Yourself|Justin Bieber|Purpose|2015",
      "Demons|Imagine Dragons|Night Visions|2012",
      "Thunder|Imagine Dragons|Evolve|2017",
      "Summer|Calvin Harris|Motion|2014",
      "Feel So Close|Calvin Harris|18 Months|2011",
      "This Is What You Came For|Calvin Harris y Rihanna|This Is What You Came For|2016",
      "One Kiss|Calvin Harris y Dua Lipa|One Kiss|2018",
      "Titanium|David Guetta y Sia|Nothing but the Beat|2011",
      "When Love Takes Over|David Guetta y Kelly Rowland|One Love|2009",
      "Wake Me Up|Avicii|True|2013",
      "Hey Brother|Avicii|True|2013",
      "Levels|Avicii|Levels|2011",
      "Don't You Worry Child|Swedish House Mafia y John Martin|Until Now|2012",
      "Give Me Everything|Pitbull y Ne-Yo y Afrojack y Nayer|Planet Pit|2011",
      "Timber|Pitbull y Kesha|Global Warming: Meltdown|2013",
      "I Know You Want Me (Calle Ocho)|Pitbull|Rebelution|2009",
      "Tik Tok|Kesha|Animal|2009",
      "Whistle|Flo Rida|Wild Ones|2012",
      "Good Feeling|Flo Rida|Wild Ones|2011",
      "Crazy|Gnarls Barkley|St. Elsewhere|2006",
      "Feel Good Inc.|Gorillaz|Demon Days|2005",
      "Clint Eastwood|Gorillaz|Gorillaz|2001",
      "One More Time|Daft Punk|Discovery|2000",
      "Call on Me|Eric Prydz|Call on Me|2004",
      "Back to Black|Amy Winehouse|Back to Black|2006",
      "Mercy|Duffy|Rockferry|2008",
      "You're Beautiful|James Blunt|Back to Bedlam|2004",
      "Chasing Cars|Snow Patrol|Eyes Open|2006",
      "Somewhere Only We Know|Keane|Hopes and Fears|2004",
      "Hey, Soul Sister|Train|Save Me, San Francisco|2009",
      "I'm Yours|Jason Mraz|We Sing. We Dance. We Steal Things.|2008",
      "Bad Day|Daniel Powter|Daniel Powter|2005",
      "Gold Digger|Kanye West y Jamie Foxx|Late Registration|2005",
      "Stronger|Kanye West|Graduation|2007",
      "Empire State of Mind|Jay-Z y Alicia Keys|The Blueprint 3|2009",
      "Fallin'|Alicia Keys|Songs in A Minor|2001",
      "No One|Alicia Keys|As I Am|2007",
      "Hotline Bling|Drake|Views|2015",
      "One Dance|Drake y Wizkid y Kyla|Views|2016",
      "God's Plan|Drake|Scorpion|2018",
      "Circles|Post Malone|Hollywood's Bleeding|2019",
      "Sunflower (Spider-Man: Into the Spider-Verse)|Post Malone y Swae Lee|Spider-Man: Into the Spider-Verse|2018",
      "Rockstar|Post Malone y 21 Savage|Beerbongs & Bentleys|2017",
      "HUMBLE.|Kendrick Lamar|DAMN.|2017",
      "Montero (Call Me by Your Name)|Lil Nas X|Montero|2021",
      "See You Again|Wiz Khalifa y Charlie Puth|Furious 7: Original Motion Picture Soundtrack|2015",
      "Thrift Shop|Macklemore y Ryan Lewis y Wanz|The Heist|2012",
      "Blurred Lines|Robin Thicke y T.I. y Pharrell Williams|Blurred Lines|2013",
      "Temperature|Sean Paul|The Trinity|2005",
      "It Wasn't Me|Shaggy y Rikrok|Hot Shot|2000",
      "Ms. Jackson|Outkast|Stankonia|2000",
      "Survivor|Destiny's Child|Survivor|2001",
      "Smack That|Akon y Eminem|Konvicted|2006",
      "Hot in Herre|Nelly|Nellyville|2002",
      "Dilemma|Nelly y Kelly Rowland|Nellyville|2002",
      "The Way I Are|Timbaland y Keri Hilson y D.O.E.|Shock Value|2007",
      "Big Girls Don't Cry|Fergie|The Dutchess|2006",
      "Hollaback Girl|Gwen Stefani|Love. Angel. Music. Baby.|2004",
      "Grace Kelly|Mika|Life in Cartoon Motion|2007",
      "Sexy and I Know It|LMFAO|Sorry for Party Rocking|2011",
      "Shut Up and Dance|Walk the Moon|Talking Is Hard|2014",
      "Feel It Still|Portugal. The Man|Woodstock|2017",
      "Heat Waves|Glass Animals|Dreamland|2020",
      "Someone You Loved|Lewis Capaldi|Divinely Uninspired to a Hellish Extent|2018",
      "Treat You Better|Shawn Mendes|Illuminate|2016",
      "Havana|Camila Cabello y Young Thug|Camila|2017",
      "Thank U, Next|Ariana Grande|Thank U, Next|2018",
      "7 Rings|Ariana Grande|Thank U, Next|2019",
      "Problem|Ariana Grande y Iggy Azalea|My Everything|2014",
      "Stay with Me|Sam Smith|In the Lonely Hour|2014",
      "All of Me|John Legend|Love in the Future|2013",
      "All About That Bass|Meghan Trainor|Title|2014",
      "Lean On|Major Lazer y DJ Snake y MØ|Peace Is the Mission|2015",
      "Closer|The Chainsmokers y Halsey|Collage|2016",
      "Stressed Out|Twenty One Pilots|Blurryface|2015",
      "7 Years|Lukas Graham|Lukas Graham|2015",
      "Dance Monkey|Tones and I|The Kids Are Coming|2019",
      "Say So|Doja Cat|Hot Pink|2019",
      "Beggin'|Måneskin|Chosen|2017",
      "Can't Get You Out of My Head|Kylie Minogue|Fever|2001",
      "Rock DJ|Robbie Williams|Sing When You're Winning|2000",
      "Beautiful Day|U2|All That You Can't Leave Behind|2000",
      "Vertigo|U2|How to Dismantle an Atomic Bomb|2004",
      "It's My Life|Bon Jovi|Crush|2000",
      "Lonely Boy|The Black Keys|El Camino|2011",
      "How You Remind Me|Nickelback|Silver Side Up|2001",
      "Sugar, We're Goin Down|Fall Out Boy|From Under the Cork Tree|2005",
      "Welcome to the Black Parade|My Chemical Romance|The Black Parade|2006",
      "Misery Business|Paramore|Riot!|2007",
      "Don't Cha|The Pussycat Dolls y Busta Rhymes|PCD|2005",
      "On the Floor|Jennifer Lopez y Pitbull|Love?|2011",
      "Hero|Enrique Iglesias|Escape|2001",
      "Summertime Sadness|Lana Del Rey|Born to Die|2012",
      "Video Games|Lana Del Rey|Born to Die|2011",
      "Love Me like You Do|Ellie Goulding|Fifty Shades of Grey: Original Motion Picture Soundtrack|2015",
      "Pompeii|Bastille|Bad Blood|2013",
      "Little Talks|Of Monsters and Men|My Head Is an Animal|2011",
      "We Are Young|Fun. y Janelle Monáe|Some Nights|2011",
      "Let Her Go|Passenger|All the Little Lights|2012",
      "Kill Bill|SZA|SOS|2022",
      "Espresso|Sabrina Carpenter|Short n' Sweet|2024",
      "Beautiful Things|Benson Boone|Fireworks & Rollerblades|2024",
      "Human|Rag'n'Bone Man|Human|2016",
    ] },
  };
  const out = {};
  for (const [id, d] of Object.entries(raw)) {
    out[id] = { name: d.name, ic: d.ic, color: d.color, songs: d.songs.map((s) => {
      const [title, artist, album, year] = s.split("|");
      return { id: id + ":" + title + ":" + artist, title, artist, album, year };
    }) };
  }
  return out;
})();
