// Video de YouTube de cada canción de los mazos ("título|artista" en minúsculas -> id del video).
window.VIDEOS = {
  "de música ligera|soda stereo": "T_FkEw27XJ0",
  "despacito|luis fonsi y daddy yankee": "kJQP7kiw5Fk",
  "hoy no me puedo levantar|mecano": "t9uHt3VUH4c",
  "billie jean|michael jackson": "Zi_XLOBDo_Y",
  "crazy in love|beyoncé": "ViwtNLUqkMY",
  "persiana americana|soda stereo": "LalPz4lIZYk",
  "échame la culpa|luis fonsi y demi lovato": "TyHvyGVs42U",
  "cruz de navajas|mecano": "2-HWcpiA8t0",
  "thriller|michael jackson": "sOnqjkJTMaA",
  "halo|beyoncé": "bnVUHWCynig",
  "prófugos|soda stereo": "eguctGjUNLI",
  "gasolina|daddy yankee": "CCF1_jI8Prk",
  "mujer contra mujer|mecano": "wVSA2CEIQ7U",
  "beat it|michael jackson": "oRdxUFDoQe0",
  "single ladies (put a ring on it)|beyoncé": "4m1EFMoRFvY",
  "nada personal|soda stereo": "LB6_e2uA7rE",
  "limbo|daddy yankee": "6BTjG-dhf5s",
  "la fuerza del destino|mecano": "_mAmEKNqg1g",
  "black or white|michael jackson": "F2AitTPI5U0",
  "hey ya!|outkast": "PWgvGjAhvIw",
  "cuando pase el temblor|soda stereo": "ZNzYr4U7Zs8",
  "hips don't lie|shakira": "DUT5rEU6pqM",
  "hawaii-bombay|mecano": "tbMWFlVoQsg",
  "bohemian rhapsody|queen": "fJ9rUzIMcZQ",
  "mr. brightside|the killers": "gAuPAKRIojM",
  "en la ciudad de la furia|soda stereo": "VoGwvVoaoCw",
  "ojos así|shakira": "5BzkbSq7pww",
  "devuélveme a mi chica|hombres g": "xBnTGGzjvlE",
  "don't stop me now|queen": "HgzGwKwLmgM",
  "seven nation army|the white stripes": "0J2QdDbelmY",
  "trátame suavemente|soda stereo": "UPVfQKUHTSc",
  "estoy aquí|shakira": "NmJHH026X0c",
  "venecia|hombres g": "jvWP6JR1saE",
  "another one bites the dust|queen": "rY0WxgSXdEE",
  "umbrella|rihanna": "CvBfHwUxHIk",
  "zoom|soda stereo": "HBO2nDIYi0E",
  "la tortura|shakira y alejandro sanz": "Dsp_8Lm1eSk",
  "marta tiene un marcapasos|hombres g": "yu3bERefTVU",
  "under pressure|queen y david bowie": "a01QQZyl-_I",
  "diamonds|rihanna": "lWA2pjMjpBs",
  "ella usó mi cabeza como un revólver|soda stereo": "1zzzby2tAQM",
  "bzrp music sessions, vol. 53|bizarrap y shakira": "CocEMWdc7Ck",
  "visite nuestro bar|hombres g": "TFqCaAVk6dY",
  "like a prayer|madonna": "79fzeNUqQbQ",
  "we found love|rihanna y calvin harris": "tg00YEETFzg",
  "demoliendo hoteles|charly garcía": "DeMCz0O7-FM",
  "livin' la vida loca|ricky martin": "p47fEXGabaY",
  "entre dos tierras|héroes del silencio": "SzimletXB7M",
  "like a virgin|madonna": "s__rX_WL100",
  "rolling in the deep|adele": "rYEDA3JcQqw",
  "promesas sobre el bidet|charly garcía": "7oMApe1k-o4",
  "maría|ricky martin": "vCEvCXuglqo",
  "maldito duende|héroes del silencio": "SqB4FSettTI",
  "material girl|madonna": "6p-lDYPR2P8",
  "someone like you|adele": "hLQl3WQQoQ0",
  "los dinosaurios|charly garcía": "BAuqozi64WQ",
  "la copa de la vida|ricky martin": "tF_ggG5dY5U",
  "la chispa adecuada (bendecida 2)|héroes del silencio": "jnDjEHyhFpU",
  "vogue|madonna": "GuJQSAiODqI",
  "rehab|amy winehouse": "KUmZp8pR1uc",
  "nos siguen pegando abajo|charly garcía": "jzO8x1pnbCk",
  "bailando|enrique iglesias": "NUsoVlDFqZg",
  "mar adentro|héroes del silencio": "slctnzJ2dzA",
  "smells like teen spirit|nirvana": "LtDlfPYzs38",
  "uptown funk|mark ronson y bruno mars": "OPf0YbXqDm0",
  "yendo de la cama al living|charly garcía": "anm5WrbbcjU",
  "corazón partío|alejandro sanz": "ZMUqIoDtSwc",
  "el baile de los que sobran|los prisioneros": "uPJrZFBiy-A",
  "sweet child o' mine|guns n' roses": "1w7OgIMMRc4",
  "locked out of heaven|bruno mars": "e-fA-gBCkj0",
  "rezo por vos|charly garcía": "kHPja5eLZdU",
  "la flaca|jarabe de palo": "r2g0pM3PMNQ",
  "tren al sur|los prisioneros": "eDipH-myZWE",
  "hotel california|eagles": "dLl4PZtxia8",
  "just the way you are|bruno mars": "LjhCEhWiKXk",
  "no voy en tren|charly garcía": "P3L10KNMptw",
  "bonito|jarabe de palo": "xxhET61yB1A",
  "we are sudamerican rockers|los prisioneros": "9NwXMDbrqA0",
  "imagine|john lennon": "VOgFZfRVaww",
  "shape of you|ed sheeran": "JGwWNGJdvx8",
  "seminare|serú girán": "JlV1pg7Wk_o",
  "rayando el sol|maná": "8lbsQyMhMT8",
  "muevan las industrias|los prisioneros": "xOKMHxQFIWE",
  "let it be|the beatles": "CGj85pVzRJs",
  "thinking out loud|ed sheeran": "lp-EO5I60KA",
  "canción para mi muerte|sui generis": "1Zjm0uh8oeA",
  "oye mi amor|maná": "h0p8yTqj8i4",
  "estrechez de corazón|los prisioneros": "nNbowGjKQHc",
  "here comes the sun|the beatles": "ssBUgHLdrCA",
  "blinding lights|the weeknd": "4NRXx6U8ABQ",
  "rasguña las piedras|sui generis": "DrKRNJGAyHw",
  "clavado en un bar|maná": "fBrX8ym3dBM",
  "el duelo|la ley": "zeUBevkD5l8",
  "yesterday|the beatles": "ogKi-58S26Y",
  "can't feel my face|the weeknd": "ex4FsWhI9Rg",
  "muchacha (ojos de papel)|almendra": "lP7_qMRIXTg",
  "la chica de ayer|nacha pop": "2pRmTJjBr6c",
  "aquí|la ley": "nTGH0Hgc7_A",
  "(i can't get no) satisfaction|the rolling stones": "nrIPxlFzDi0",
  "starboy|the weeknd y daft punk": "34Na4j8AVgA",
  "barro tal vez|luis alberto spinetta": "W47hOuQjDag",
  "me colé en una fiesta|mecano": "FvVoBFxtHC8",
  "mentira|la ley": "d1dcXgGQT2M",
  "like a rolling stone|bob dylan": "IwOfCgkyEj0",
  "bad guy|billie eilish": "DyDfgMOUjCI",
  "seguir viviendo sin tu amor|luis alberto spinetta": "78H_YPqNuCo",
  "hijo de la luna|mecano": "OwGG5fX7bxY",
  "la ingrata|café tacvba": "kIr8hsVTCzg",
  "respect|aretha franklin": "A134hShx_gw",
  "happy|pharrell williams": "ZbZSe6N_BXs",
  "durazno sangrando|invisible": "i4_pVlJdbEY",
  "torero|chayanne": "GuZzuQvv7uc",
  "las flores|café tacvba": "zJvMwTgWcP0",
  "wonderwall|oasis": "6hzrDeceEKc",
  "get lucky|daft punk y pharrell williams": "5NV6Rdv1a3I",
  "ji ji ji|patricio rey y sus redonditos de ricota": "CnJqYsSOgfg",
  "vivir mi vida|marc anthony": "YXnjy5YlDwk",
  "eres|café tacvba": "98Akpf1ph2o",
  "with or without you|u2": "ujNeHIo7oTE",
  "poker face|lady gaga": "bESGLojNYSo",
  "un poco de amor francés|patricio rey y sus redonditos de ricota": "WlFLpKaC4_c",
  "la gozadera|gente de zona y marc anthony": "VMp55KH_3wo",
  "chilanga banda|café tacvba": "bKjn26agAEs",
  "every breath you take|the police": "OMOGaugKpzs",
  "just dance|lady gaga": "2Abk1jAONjw",
  "juguetes perdidos|patricio rey y sus redonditos de ricota": "rZb4PGFBB3o",
  "danza kuduro|don omar y lucenzo": "7zp1TbLFPp8",
  "maría|café tacvba": "LWpNWWXNy5I",
  "take on me|a-ha": "djV11Xbc914",
  "bad romance|lady gaga": "qrO4YZeyl0I",
  "flaca|andrés calamaro": "UCF9oHXhDMU",
  "dákiti|bad bunny y jhayco": "TmKh7lAwnBI",
  "afuera|caifanes": "gBt1jOtKz6Y",
  "livin' on a prayer|bon jovi": "lDK9QqIzhwk",
  "shallow|lady gaga y bradley cooper": "bo_efYhYU2A",
  "crímenes perfectos|andrés calamaro": "QL_S9W2G8tI",
  "tití me preguntó|bad bunny": "Cr8K88UcO0s",
  "no dejes que...|caifanes": "i17Go6G-siA",
  "africa|toto": "FTQbiNvZqaY",
  "viva la vida|coldplay": "dvgZkm1xWPE",
  "mil horas|los abuelos de la nada": "5IR5CdvBQPY",
  "me porto bonito|bad bunny y chencho corleone": "saGYMhApaH8",
  "la célula que explota|caifanes": "LltlG9sU6zg",
  "girls just want to have fun|cyndi lauper": "PIb6AZdTr-A",
  "yellow|coldplay": "yKNxeF4KMsY",
  "costumbres argentinas|los abuelos de la nada": "J0xdIDXd2Tw",
  "hawái|maluma": "pK060iUFWXg",
  "viento|caifanes": "T8TtE-enslA",
  "time after time|cyndi lauper": "VdQY7BusJNU",
  "clocks|coldplay": "d020hcWA_Wg",
  "matador|los fabulosos cadillacs": "pjPA7CXutDw",
  "felices los 4|maluma": "t_jHrUE5IOk",
  "en el muelle de san blas|maná": "teprNzF6J1I",
  "i will survive|gloria gaynor": "6dYWe1c3OyU",
  "numb|linkin park": "kXYiU_JCYtU",
  "mal bicho|los fabulosos cadillacs": "m0Lc9pjFzm4",
  "tusa|karol g y nicki minaj": "tbneQDc2H3I",
  "vivir sin aire|maná": "g3uxeG1rrlE",
  "stayin' alive|bee gees": "fNFzfwLM72c",
  "in the end|linkin park": "eVTXPUF4Oz4",
  "siguiendo la luna|los fabulosos cadillacs": "cl5HbmhEUBM",
  "propuesta indecente|romeo santos": "QFs3PIZb3js",
  "labios compartidos|maná": "1IgOZaQqB58",
  "dancing queen|abba": "xFrGuyw1V8s",
  "somebody that i used to know|gotye": "8UVNT4wvIGY",
  "lamento boliviano|enanitos verdes": "hReAuaAuJOE",
  "obsesión|aventura": "8_QY5gFQUTg",
  "mariposa traicionera|maná": "av3wkasS-WQ",
  "le freak|chic": "aXgSHL7efKg",
  "toxic|britney spears": "LOZuxwVk7TU",
  "la muralla verde|enanitos verdes": "tYGZ1YCD2YU",
  "suavemente|elvis crespo": "WPiEbYSF9kE",
  "gimme the power|molotov": "9YI4aqaVSg0"
};
