// Video de YouTube de cada canción de los mazos ("título|artista" en minúsculas -> id del video).
window.VIDEOS = {
  "de música ligera|soda stereo": "T_FkEw27XJ0",
  "despacito|luis fonsi y daddy yankee": "kJQP7kiw5Fk",
  "hoy no me puedo levantar|mecano": "t9uHt3VUH4c",
  "billie jean|michael jackson": "Zi_XLOBDo_Y",
  "crazy in love|beyoncé": "ViwtNLUqkMY",
  "persiana americana|soda stereo": "LalPz4lIZYk",
  "échame la culpa|luis fonsi y demi lovato": "TyHvyGVs42U",
  "cruz de navajas|mecano": "2-HWcpiA8t0",
  "thriller|michael jackson": "sOnqjkJTMaA",
  "halo|beyoncé": "bnVUHWCynig",
  "prófugos|soda stereo": "eguctGjUNLI",
  "gasolina|daddy yankee": "CCF1_jI8Prk",
  "mujer contra mujer|mecano": "wVSA2CEIQ7U",
  "beat it|michael jackson": "oRdxUFDoQe0",
  "single ladies (put a ring on it)|beyoncé": "4m1EFMoRFvY",
  "nada personal|soda stereo": "LB6_e2uA7rE",
  "limbo|daddy yankee": "6BTjG-dhf5s",
  "la fuerza del destino|mecano": "_mAmEKNqg1g",
  "black or white|michael jackson": "F2AitTPI5U0",
  "hey ya!|outkast": "PWgvGjAhvIw",
  "cuando pase el temblor|soda stereo": "ZNzYr4U7Zs8",
  "hips don't lie|shakira": "DUT5rEU6pqM",
  "hawaii-bombay|mecano": "tbMWFlVoQsg",
  "bohemian rhapsody|queen": "fJ9rUzIMcZQ",
  "mr. brightside|the killers": "gAuPAKRIojM",
  "en la ciudad de la furia|soda stereo": "VoGwvVoaoCw",
  "ojos así|shakira": "5BzkbSq7pww",
  "devuélveme a mi chica|hombres g": "xBnTGGzjvlE",
  "don't stop me now|queen": "HgzGwKwLmgM",
  "seven nation army|the white stripes": "0J2QdDbelmY",
  "trátame suavemente|soda stereo": "UPVfQKUHTSc",
  "estoy aquí|shakira": "NmJHH026X0c",
  "venecia|hombres g": "jvWP6JR1saE",
  "another one bites the dust|queen": "rY0WxgSXdEE",
  "umbrella|rihanna": "CvBfHwUxHIk",
  "zoom|soda stereo": "HBO2nDIYi0E",
  "la tortura|shakira y alejandro sanz": "Dsp_8Lm1eSk",
  "marta tiene un marcapasos|hombres g": "yu3bERefTVU",
  "under pressure|queen y david bowie": "a01QQZyl-_I",
  "diamonds|rihanna": "lWA2pjMjpBs",
  "ella usó mi cabeza como un revólver|soda stereo": "1zzzby2tAQM",
  "bzrp music sessions, vol. 53|bizarrap y shakira": "CocEMWdc7Ck",
  "visite nuestro bar|hombres g": "TFqCaAVk6dY",
  "like a prayer|madonna": "79fzeNUqQbQ",
  "we found love|rihanna y calvin harris": "tg00YEETFzg",
  "demoliendo hoteles|charly garcía": "DeMCz0O7-FM",
  "livin' la vida loca|ricky martin": "p47fEXGabaY",
  "entre dos tierras|héroes del silencio": "SzimletXB7M",
  "like a virgin|madonna": "s__rX_WL100",
  "rolling in the deep|adele": "rYEDA3JcQqw",
  "promesas sobre el bidet|charly garcía": "7oMApe1k-o4",
  "maría|ricky martin": "vCEvCXuglqo",
  "maldito duende|héroes del silencio": "SqB4FSettTI",
  "material girl|madonna": "6p-lDYPR2P8",
  "someone like you|adele": "hLQl3WQQoQ0",
  "los dinosaurios|charly garcía": "BAuqozi64WQ",
  "la copa de la vida|ricky martin": "tF_ggG5dY5U",
  "la chispa adecuada (bendecida 2)|héroes del silencio": "jnDjEHyhFpU",
  "vogue|madonna": "GuJQSAiODqI",
  "rehab|amy winehouse": "KUmZp8pR1uc",
  "nos siguen pegando abajo|charly garcía": "jzO8x1pnbCk",
  "bailando|enrique iglesias": "NUsoVlDFqZg",
  "mar adentro|héroes del silencio": "slctnzJ2dzA",
  "smells like teen spirit|nirvana": "LtDlfPYzs38",
  "uptown funk|mark ronson y bruno mars": "OPf0YbXqDm0",
  "yendo de la cama al living|charly garcía": "anm5WrbbcjU",
  "corazón partío|alejandro sanz": "ZMUqIoDtSwc",
  "el baile de los que sobran|los prisioneros": "uPJrZFBiy-A",
  "sweet child o' mine|guns n' roses": "1w7OgIMMRc4",
  "locked out of heaven|bruno mars": "e-fA-gBCkj0",
  "rezo por vos|charly garcía": "kHPja5eLZdU",
  "la flaca|jarabe de palo": "r2g0pM3PMNQ",
  "tren al sur|los prisioneros": "eDipH-myZWE",
  "hotel california|eagles": "dLl4PZtxia8",
  "just the way you are|bruno mars": "LjhCEhWiKXk",
  "no voy en tren|charly garcía": "P3L10KNMptw",
  "bonito|jarabe de palo": "xxhET61yB1A",
  "we are sudamerican rockers|los prisioneros": "9NwXMDbrqA0",
  "imagine|john lennon": "VOgFZfRVaww",
  "shape of you|ed sheeran": "JGwWNGJdvx8",
  "seminare|serú girán": "JlV1pg7Wk_o",
  "rayando el sol|maná": "8lbsQyMhMT8",
  "muevan las industrias|los prisioneros": "xOKMHxQFIWE",
  "let it be|the beatles": "CGj85pVzRJs",
  "thinking out loud|ed sheeran": "lp-EO5I60KA"
};
